LEMON?=$(shell command -v lemon 2>/dev/null)
# I installed via apt
RE2C=re2c
# I pulled the file from http://www.hwaci.com/sw/mkhdr/makeheaders.c here, then
# ran `gcc makeheaders.c -o makeheaders`
MAKEHEADERS=~/repositories/makeheaders/makeheaders

GTEST_DIR=$(HOME)/repositories/googletest/googletest
# Homebrew prefixes (used if available)
BREW?=brew
GTEST_PREFIX?=$(shell $(BREW) --prefix googletest 2>/dev/null)
YAML_PREFIX?=$(shell $(BREW) --prefix yaml-cpp 2>/dev/null)
BENCH_PREFIX?=$(shell $(BREW) --prefix google-benchmark 2>/dev/null)
NAME=omnomnum

WARN=-Wall -W -Wno-missing-field-initializers

# Enable scanner-side fraction recognition by default
CCFLAGS += -DSCANNER_FRACTIONS=1
CXXFLAGS += -DSCANNER_FRACTIONS=1

all: CXXFLAGS += -DNDEBUG -O3 -msse4.2 -std=c++11 -pedantic
all: CCFLAGS += -DNDEBUG -O3 -msse4.2 -std=c99 -pedantic
all: omnomnum

debug: CXXFLAGS += -DDEBUG -g -ggdb -Dprint_errors -O1 -std=c++11 -pedantic
debug: CCFLAGS += -DDEBUG -g -ggdb -Dprint_errors -O1 -std=c99 -pedantic
debug: omnomnum

FINAL_CFLAGS=$(STD) $(WARN) $(CCFLAGS)
FINAL_CXXFLAGS=$(WARN) $(CXXFLAGS)
FINAL_LDFLAGS=$(STD) $(WARN) $(LDFLAGS)
FINAL_LIBS=-lm

OMNOMNUM_CC=$(CC) $(FINAL_CFLAGS)
OMNOMNUM_CXX=$(CXX) $(FINAL_CXXFLAGS)

# Use at least C++17 for GoogleTest >= 1.14
CXX17FLAGS=-std=c++17

# Build metadata for stamping benchmark binaries
GIT_SHA:=$(shell git rev-parse --short=12 HEAD 2>/dev/null || echo unknown)
GIT_DESC:=$(shell git describe --always --dirty --tags 2>/dev/null || git rev-parse --short=12 HEAD 2>/dev/null || echo unknown)
BUILD_TIME:=$(shell date -u +%FT%TZ)
GIT_DIRTY:=$(shell test -n "$$(git status --porcelain 2>/dev/null)" && echo 1 || echo 0)

OMNOMNUM_OBJ=parser.o parser_compat.o omnomnum.o scanner.o scan.o sds.o itoa.o dtoa.o scanner.def.o util.o grisu2/grisu2.o branchlut/branchlut.o
DEPS=parser.h scan.h omnomnum.h scanner.h

test/cases.yaml: ;
test/remove_char_inplace.yaml: ;

branchlut/branchlut.o: branchlut/branchlut.c $(DEPS)
	$(OMNOMNUM_CC) -c $< -o branchlut/branchlut.o

grisu2/grisu2.o: grisu2/grisu2.c $(DEPS)
	$(OMNOMNUM_CC) -c $< -o grisu2/grisu2.o

# Only use the generic C compile rule for core objects, not tests
$(OMNOMNUM_OBJ): %.o: %.c $(DEPS)
	$(OMNOMNUM_CC) -c $<

omnomnum: $(OMNOMNUM_OBJ) main.o
	$(OMNOMNUM_CC) $^ -o $@ $(FINAL_LIBS)
	#./omnomnum

parser.c: parser.yy scanner.re
	# produces parser.c (ignore non-zero exit due to conflicts)
	-$(LEMON) -m parser.yy || true

parser.h: parser.c
	@echo "/* Autogenerated from parser.c. Do not edit by hand. */" > parser.h
	@echo '#include <stdio.h>' >> parser.h
	@echo '#ifndef YYMALLOCARGTYPE' >> parser.h
	@echo '# define YYMALLOCARGTYPE size_t' >> parser.h
	@echo '#endif' >> parser.h
	@echo '#define ParseTOKENTYPE  YYSTYPE' >> parser.h
	@echo '#define ParseARG_PDECL , ParserState *state' >> parser.h
	@echo 'void Parse(void *yyp,int yymajor,ParseTOKENTYPE yyminor ParseARG_PDECL);' >> parser.h
	@echo 'void ParseReset(void *p);' >> parser.h
	@echo '#if defined(YYTRACKMAXSTACKDEPTH)' >> parser.h
	@echo 'int ParseStackPeak(void *p);' >> parser.h
	@echo '#endif' >> parser.h
	@echo 'void ParseFree(void *p,void(*freeProc)(void *));' >> parser.h
	@echo 'void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE));' >> parser.h
	@echo '#if !defined(NDEBUG)' >> parser.h
	@echo 'void ParseTrace(FILE *TraceFILE,char *zTracePrompt);' >> parser.h
	@echo '#endif' >> parser.h
	@echo '#define ParseARG_STORE yypParser->state  = state;' >> parser.h
	@echo '#define ParseARG_FETCH  ParserState *state  = yypParser->state;' >> parser.h
	@echo '#define ParseARG_SDECL  ParserState *state ;' >> parser.h
	@echo '#ifndef ParseCTX_SDECL' >> parser.h
	@echo '#define ParseCTX_SDECL' >> parser.h
	@echo '#endif' >> parser.h
	@echo '#ifndef ParseCTX_PDECL' >> parser.h
	@echo '#define ParseCTX_PDECL' >> parser.h
	@echo '#endif' >> parser.h
	@echo '#ifndef ParseCTX_PARAM' >> parser.h
	@echo '#define ParseCTX_PARAM' >> parser.h
	@echo '#endif' >> parser.h
	@echo '#ifndef ParseCTX_FETCH' >> parser.h
	@echo '#define ParseCTX_FETCH' >> parser.h
	@echo '#endif' >> parser.h
	@echo '#ifndef ParseCTX_STORE' >> parser.h
	@echo '#define ParseCTX_STORE' >> parser.h
	@echo '#endif' >> parser.h
	@# Append token defines extracted from parser.c
	@sed -n '/^#if INTERFACE/,/^#endif/p' parser.c | grep '^#define TOKEN_' >> parser.h || true
	@echo '#define INTERFACE 0' >> parser.h

parser.o: parser.h
	# produces parser.o
	$(OMNOMNUM_CC) -c parser.c

scanner.c: scanner.re parser.yy parser.h
	#$(RE2C) -d -o $@ scanner.re
	$(RE2C) -o $@ scanner.re

clean:
	rm -rf *.o test/*.o parser.out parser.c scanner.o scanner.c main.o omnomnum *.gch test/test_omnomnum test/test_benchmark

.PHONY: all clean

test/test_omnomnum.o: parser.h scan.h omnomnum.h scanner.h test/test_omnomnum.c
	$(OMNOMNUM_CXX) $(CXX17FLAGS) -I$(GTEST_PREFIX)/include -I$(YAML_PREFIX)/include -c test/test_omnomnum.c -o $@

test/test_omnomnum: $(OMNOMNUM_OBJ) test/test_omnomnum.o
	$(OMNOMNUM_CXX) $(CXX17FLAGS) -o $@ -I$(GTEST_PREFIX)/include -I. $^ -pthread -L$(GTEST_PREFIX)/lib -lgtest -lgtest_main -L$(YAML_PREFIX)/lib -lyaml-cpp

test/test_util.o: util.h test/test_util.c
	$(CXX) $(CXX17FLAGS) -I$(GTEST_PREFIX)/include -I$(YAML_PREFIX)/include -c test/test_util.c -o $@

test/test_util: util.o test/test_util.o
	$(CXX) $(CXX17FLAGS) -o $@ -I$(GTEST_PREFIX)/include -I. $^ -pthread -L$(GTEST_PREFIX)/lib -lgtest -lgtest_main -L$(YAML_PREFIX)/lib -lyaml-cpp

test_util: test/test_util test/remove_char_inplace.yaml
	cd test && ./test_util

test: all test/test_omnomnum test/cases.yaml
	cd test && ./test_omnomnum

test/test_benchmark.o: parser.h scan.h omnomnum.h scanner.h test/test_benchmark.c
	$(CXX) $(CXX17FLAGS) -I$(BENCH_PREFIX)/include \
		-DGIT_SHA=\"$(GIT_SHA)\" \
		-DGIT_DESC=\"$(GIT_DESC)\" \
		-DBUILD_TIME=\"$(BUILD_TIME)\" \
		-DTREE_DIRTY_STR=\"$(GIT_DIRTY)\" \
		-c test/test_benchmark.c -o $@

test/test_benchmark: $(OMNOMNUM_OBJ) test/test_benchmark.o
	$(CXX) $(CXX17FLAGS) -o $@ -I. $^ -pthread -L$(BENCH_PREFIX)/lib -lbenchmark

# Lightweight local benchmark (fallback when google-benchmark cannot run)
bench_local: $(OMNOMNUM_OBJ) bench_local.o
	$(OMNOMNUM_CC) -O3 -o $@ -I. $^ $(FINAL_LIBS)

bench_local.o: bench_local.c $(DEPS)
	$(OMNOMNUM_CC) -O3 -c bench_local.c -o $@

# Default benchmark target runs Google Benchmark binary
benchmark: all test/test_benchmark
	cd test && ./test_benchmark --benchmark_min_time=2s --benchmark_repetitions=3 --benchmark_out=benchmark.json --benchmark_out_format=json

.PHONY: bench-before bench-after bench-local-before bench-local-after

# Build and run Google Benchmark with fraction post-pass disabled
bench-before:
	$(MAKE) clean
	$(MAKE) test/test_benchmark CCFLAGS="$(CCFLAGS) -DSCANNER_FRACTIONS=0" CXXFLAGS="$(CXXFLAGS) -DSCANNER_FRACTIONS=0"
	cd test && ./test_benchmark --benchmark_min_time=2s --benchmark_repetitions=3 --benchmark_out=before.json --benchmark_out_format=json

# Build and run Google Benchmark with current code (post-pass enabled)
bench-after:
	$(MAKE) clean
	$(MAKE) test/test_benchmark CCFLAGS="$(CCFLAGS) -DSCANNER_FRACTIONS=1" CXXFLAGS="$(CXXFLAGS) -DSCANNER_FRACTIONS=1"
	cd test && ./test_benchmark --benchmark_min_time=2s --benchmark_repetitions=3 --benchmark_out=after.json --benchmark_out_format=json

# Fallback micro-benchmarks (no Google Benchmark, works in restricted envs)
bench-local-before:
	$(MAKE) clean
	$(MAKE) bench_local CCFLAGS="$(CCFLAGS) -DSCANNER_FRACTIONS=0"
	./bench_local

bench-local-after:
	$(MAKE) clean
	$(MAKE) bench_local
	./bench_local

# (Removed internal and gprof profiling helpers)
