LEMON?=$(shell command -v lemon 2>/dev/null)
# I installed via apt
RE2C?=$(shell command -v re2c 2>/dev/null)
# I pulled the file from http://www.hwaci.com/sw/mkhdr/makeheaders.c here, then
# ran `gcc makeheaders.c -o makeheaders`
MAKEHEADERS=~/repositories/makeheaders/makeheaders

GTEST_DIR=$(HOME)/repositories/googletest/googletest
# Homebrew prefixes (used if available)
BREW?=brew
GTEST_PREFIX?=$(shell $(BREW) --prefix googletest 2>/dev/null)
YAML_PREFIX?=$(shell $(BREW) --prefix yaml-cpp 2>/dev/null)
BENCH_PREFIX?=$(shell $(BREW) --prefix google-benchmark 2>/dev/null)
NAME=omnomnum

WARN=-Wall -W -Wno-missing-field-initializers

# Enable scanner-side fraction recognition by default
CCFLAGS += -DSCANNER_FRACTIONS=1
CXXFLAGS += -DSCANNER_FRACTIONS=1

# Optional LTO (set USE_LTO=thin or USE_LTO=full/1)
ifeq ($(USE_LTO),thin)
  LTO_FLAGS := -flto=thin
else ifneq (,$(filter $(USE_LTO),1 full yes TRUE true))
  LTO_FLAGS := -flto
else
  LTO_FLAGS :=
endif
CCFLAGS += $(LTO_FLAGS)
CXXFLAGS += $(LTO_FLAGS)
LDFLAGS += $(LTO_FLAGS)

# Architecture-conditional flags (avoid x86-only flags on arm64)
ARCH:=$(shell uname -m)
ARCH_FLAGS:=
ifneq (,$(filter x86_64 i386 i686 amd64,$(ARCH)))
ARCH_FLAGS += -msse4.2
endif

all: CXXFLAGS += -DNDEBUG -O3 $(ARCH_FLAGS) -std=c++11 -pedantic
all: CCFLAGS += -DNDEBUG -O3 $(ARCH_FLAGS) -std=c99 -pedantic
all: omnomnum

debug: CXXFLAGS += -DDEBUG -g -ggdb -Dprint_errors -O1 -std=c++11 -pedantic
debug: CCFLAGS += -DDEBUG -g -ggdb -Dprint_errors -O1 -std=c99 -pedantic
debug: omnomnum

FINAL_CFLAGS=$(STD) $(WARN) $(CCFLAGS)
FINAL_CXXFLAGS=$(WARN) $(CXXFLAGS)
FINAL_LDFLAGS=$(STD) $(WARN) $(LDFLAGS)
FINAL_LIBS=-lm

OMNOMNUM_CC=$(CC) $(FINAL_CFLAGS)
OMNOMNUM_CXX=$(CXX) $(FINAL_CXXFLAGS)

# Use at least C++17 for GoogleTest >= 1.14
CXX17FLAGS=-std=c++17

# Build metadata for stamping benchmark binaries
GIT_SHA:=$(shell git rev-parse --short=12 HEAD 2>/dev/null || echo unknown)
GIT_DESC:=$(shell git describe --always --dirty --tags 2>/dev/null || git rev-parse --short=12 HEAD 2>/dev/null || echo unknown)
BUILD_TIME:=$(shell date -u +%FT%TZ)
GIT_DIRTY:=$(shell test -n "$$(git status --porcelain 2>/dev/null)" && echo 1 || echo 0)

CORE_OBJS=parser_compat.o omnomnum.o scanner.o scan.o sds.o itoa.o dtoa.o scanner.def.o util.o
OMNOMNUM_OBJ=$(CORE_OBJS) parser.o grisu2/grisu2.o branchlut/branchlut.o
DEPS=parser.h scan.h omnomnum.h scanner.h

test/cases.yaml: ;
test/remove_char_inplace.yaml: ;


# Only use the generic C compile rule for core objects, not tests
$(CORE_OBJS): %.o: %.c $(DEPS)
	$(OMNOMNUM_CC) -c $< -o $@

# parser_compat needs stack depth tracking enabled
parser_compat.o: parser_compat.c $(DEPS)
	$(OMNOMNUM_CC) -DYYTRACKMAXSTACKDEPTH -c $< -o $@

branchlut/branchlut.o: branchlut/branchlut.c $(DEPS)
	$(OMNOMNUM_CC) -c $< -o $@

grisu2/grisu2.o: grisu2/grisu2.c $(DEPS)
	$(OMNOMNUM_CC) -c $< -o $@

omnomnum: $(OMNOMNUM_OBJ) main.o
	$(OMNOMNUM_CC) $^ -o $@ $(FINAL_LIBS)
	#./omnomnum
	@# Optionally strip symbols in optimized builds (ignore if strip unsupported)
	@if command -v strip >/dev/null 2>&1; then strip -x $@ 2>/dev/null || true; fi

# Generated files are checked into git for stable builds without lemon/re2c
# Use 'make regen' to regenerate parser.c/parser.h/scanner.c if you modify parser.yy or scanner.re
parser.c: parser.yy scanner.re
	@if [ -z "$(LEMON)" ]; then \
		echo "Error: lemon not found. parser.c is checked into git; use existing file or install lemon to regenerate."; \
		echo "Continuing with existing parser.c..."; \
	else \
		echo "# Regenerating parser.c with lemon"; \
		$(LEMON) -m parser.yy || true; \
	fi

parser.h: parser.c
	@if [ ! -f parser.c ]; then \
		echo "Error: parser.c not found. Cannot generate parser.h"; \
		exit 1; \
	fi
	@echo "# Generating parser.h from parser.c"
	@echo "/* Autogenerated from parser.c. Do not edit by hand. */" > parser.h
	@echo '#include <stdio.h>' >> parser.h
	@echo '#ifndef YYMALLOCARGTYPE' >> parser.h
	@echo '# define YYMALLOCARGTYPE size_t' >> parser.h
	@echo '#endif' >> parser.h
	@echo '#define ParseTOKENTYPE  YYSTYPE' >> parser.h
	@echo '#define ParseARG_PDECL , ParserState *state' >> parser.h
	@echo 'void Parse(void *yyp,int yymajor,ParseTOKENTYPE yyminor ParseARG_PDECL);' >> parser.h
	@echo 'void ParseReset(void *p);' >> parser.h
	@echo '#if defined(YYTRACKMAXSTACKDEPTH)' >> parser.h
	@echo 'int ParseStackPeak(void *p);' >> parser.h
	@echo '#endif' >> parser.h
	@echo 'void ParseFree(void *p,void(*freeProc)(void *));' >> parser.h
	@echo 'void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE));' >> parser.h
	@echo '#if !defined(NDEBUG)' >> parser.h
	@echo 'void ParseTrace(FILE *TraceFILE,char *zTracePrompt);' >> parser.h
	@echo '#endif' >> parser.h
	@echo '#define ParseARG_STORE yypParser->state  = state;' >> parser.h
	@echo '#define ParseARG_FETCH  ParserState *state  = yypParser->state;' >> parser.h
	@echo '#define ParseARG_SDECL  ParserState *state ;' >> parser.h
	@echo '#ifndef ParseCTX_SDECL' >> parser.h
	@echo '#define ParseCTX_SDECL' >> parser.h
	@echo '#endif' >> parser.h
	@echo '#ifndef ParseCTX_PDECL' >> parser.h
	@echo '#define ParseCTX_PDECL' >> parser.h
	@echo '#endif' >> parser.h
	@echo '#ifndef ParseCTX_PARAM' >> parser.h
	@echo '#define ParseCTX_PARAM' >> parser.h
	@echo '#endif' >> parser.h
	@echo '#ifndef ParseCTX_FETCH' >> parser.h
	@echo '#define ParseCTX_FETCH' >> parser.h
	@echo '#endif' >> parser.h
	@echo '#ifndef ParseCTX_STORE' >> parser.h
	@echo '#define ParseCTX_STORE' >> parser.h
	@echo '#endif' >> parser.h
	@# Append token defines extracted from parser.c
	@sed -n '/^#if INTERFACE/,/^#endif/p' parser.c | grep '^#define TOKEN_' >> parser.h || true
	@echo '#define INTERFACE 0' >> parser.h

parser.o: parser.h
	# produces parser.o with stack depth tracking enabled
	$(OMNOMNUM_CC) -DYYTRACKMAXSTACKDEPTH -c parser.c

scanner.c: scanner.re parser.yy parser.h
	@if [ -z "$(RE2C)" ] || ! command -v $(RE2C) >/dev/null 2>&1; then \
		echo "Error: re2c not found. scanner.c is checked into git; use existing file or install re2c to regenerate."; \
		echo "Continuing with existing scanner.c..."; \
	else \
		echo "# Regenerating scanner.c with re2c"; \
		$(RE2C) -o $@ scanner.re; \
	fi

# Regenerate parser and scanner from sources (requires lemon and re2c)
.PHONY: regen
regen:
	@if [ -z "$(LEMON)" ] || [ -z "$(RE2C)" ]; then \
		echo "Error: Cannot regenerate - lemon or re2c not found"; \
		echo "  LEMON=$(LEMON)"; \
		echo "  RE2C=$(RE2C)"; \
		exit 1; \
	fi
	rm -f parser.c parser.h scanner.c
	$(MAKE) parser.c parser.h scanner.c

# Regenerate gperf perfect hash for denominator words
# This updates scanner.re with the new hash table and regenerates scanner.c
.PHONY: regen-gperf
regen-gperf:
	@if [ ! -f "scripts/regenerate_gperf.sh" ]; then \
		echo "Error: scripts/regenerate_gperf.sh not found"; \
		exit 1; \
	fi
	@./scripts/regenerate_gperf.sh

# Standard clean - preserves generated files checked into git
clean:
	rm -rf *.o test/*.o parser.out main.o omnomnum *.gch test/test_omnomnum test/test_benchmark

# Deep clean - removes generated files too (requires lemon/re2c to rebuild)
.PHONY: distclean
distclean: clean
	rm -rf parser.c parser.h scanner.c

.PHONY: all clean

test/test_omnomnum.o: parser.h scan.h omnomnum.h scanner.h test/test_omnomnum.c
	$(OMNOMNUM_CXX) $(CXX17FLAGS) -I$(GTEST_PREFIX)/include -I$(YAML_PREFIX)/include -c test/test_omnomnum.c -o $@

test/test_omnomnum: $(OMNOMNUM_OBJ) test/test_omnomnum.o
	$(OMNOMNUM_CXX) $(CXX17FLAGS) $(FINAL_LDFLAGS) -o $@ -I$(GTEST_PREFIX)/include -I. $^ -pthread -L$(GTEST_PREFIX)/lib -lgtest -lgtest_main -L$(YAML_PREFIX)/lib -lyaml-cpp

test/test_util.o: util.h test/test_util.c
	$(CXX) $(CXX17FLAGS) -I$(GTEST_PREFIX)/include -I$(YAML_PREFIX)/include -c test/test_util.c -o $@

test/test_util: util.o test/test_util.o
	$(CXX) $(CXX17FLAGS) -o $@ -I$(GTEST_PREFIX)/include -I. $^ -pthread -L$(GTEST_PREFIX)/lib -lgtest -lgtest_main -L$(YAML_PREFIX)/lib -lyaml-cpp

test_util: test/test_util test/remove_char_inplace.yaml
	cd test && ./test_util

test: all test/test_omnomnum test/cases.yaml
	cd test && ./test_omnomnum

test/test_benchmark.o: parser.h scan.h omnomnum.h scanner.h test/test_benchmark.c
	$(CXX) $(CXX17FLAGS) -I$(BENCH_PREFIX)/include \
		-DGIT_SHA=\"$(GIT_SHA)\" \
		-DGIT_DESC=\"$(GIT_DESC)\" \
		-DBUILD_TIME=\"$(BUILD_TIME)\" \
		-DTREE_DIRTY_STR=\"$(GIT_DIRTY)\" \
		-c test/test_benchmark.c -o $@

test/test_benchmark: $(OMNOMNUM_OBJ) test/test_benchmark.o
	$(CXX) $(CXX17FLAGS) $(FINAL_LDFLAGS) -o $@ -I. $^ -pthread -L$(BENCH_PREFIX)/lib -lbenchmark

# Lightweight local benchmark (fallback when google-benchmark cannot run)
bench_local: $(OMNOMNUM_OBJ) bench_local.o
	$(OMNOMNUM_CC) -O3 $(FINAL_LDFLAGS) -o $@ -I. $^ $(FINAL_LIBS)

bench_local.o: bench_local.c $(DEPS)
	$(OMNOMNUM_CC) -O3 -c bench_local.c -o $@

# Benchmark targets using optimized configurations from BENCHMARK_RECOMMENDATIONS.md
.PHONY: benchmark benchmark-fast benchmark-accurate benchmark-compare

# Fast mode: 0.05s min_time, 5 reps (~9s, 2.11% CV of means)
# Use for: Quick iteration during development
benchmark-fast: all test/test_benchmark
	BENCH_MODE=fast bash scripts/benchmark_current.sh test/benchmark-fast.json

# Default mode: 0.1s min_time, 10 reps (~32s, 2.02% CV of means) - RECOMMENDED
# Use for: CI/CD pipelines, pre-merge testing
benchmark: all test/test_benchmark
	bash scripts/benchmark_current.sh test/benchmark.json

# Accurate mode: 0.2s min_time, 10 reps (~64s, 1.40% CV of means)
# Use for: Official releases, performance validation
benchmark-accurate: all test/test_benchmark
	BENCH_MODE=accurate bash scripts/benchmark_current.sh test/benchmark-accurate.json

# Compare mode: Run benchmark multiple times and analyze CV of means
# Example: make benchmark-compare COMPARE_RUNS=5
benchmark-compare: all test/test_benchmark
	COMPARE_MODE=1 COMPARE_RUNS=$${COMPARE_RUNS:-5} bash scripts/benchmark_current.sh test/benchmark-compare.json

.PHONY: bench-before bench-after bench-local-before bench-local-after

# Build and run Google Benchmark with fraction post-pass disabled
bench-before:
	$(MAKE) clean
	$(MAKE) test/test_benchmark CCFLAGS="$(CCFLAGS) -DSCANNER_FRACTIONS=0" CXXFLAGS="$(CXXFLAGS) -DSCANNER_FRACTIONS=0"
	cd test && ./test_benchmark --benchmark_min_time=2s --benchmark_repetitions=3 --benchmark_out=before.json --benchmark_out_format=json

# Build and run Google Benchmark with current code (post-pass enabled)
bench-after:
	$(MAKE) clean
	$(MAKE) test/test_benchmark CCFLAGS="$(CCFLAGS) -DSCANNER_FRACTIONS=1" CXXFLAGS="$(CXXFLAGS) -DSCANNER_FRACTIONS=1"
	cd test && ./test_benchmark --benchmark_min_time=2s --benchmark_repetitions=3 --benchmark_out=after.json --benchmark_out_format=json

# Fallback micro-benchmarks (no Google Benchmark, works in restricted envs)
bench-local-before:
	$(MAKE) clean
	$(MAKE) bench_local CCFLAGS="$(CCFLAGS) -DSCANNER_FRACTIONS=0"
	./bench_local

bench-local-after:
	$(MAKE) clean
	$(MAKE) bench_local
	./bench_local

# (Removed internal and gprof profiling helpers)

# Convenience alias
release: all

# Profile-Guided Optimization build
# Builds binary with runtime profiling, generates profile data, then rebuilds with optimizations
.PHONY: pgo pgo-clean
pgo:
	@echo "=== Building with Profile-Guided Optimization ==="
	@echo "Step 1/3: Building instrumented binary..."
	$(MAKE) clean
	$(MAKE) test/test_benchmark \
		CCFLAGS="$(CCFLAGS) -fprofile-generate" \
		CXXFLAGS="$(CXXFLAGS) -fprofile-generate" \
		LDFLAGS="$(LDFLAGS) -fprofile-generate"
	@echo "Step 2/3: Generating profile data (this may take a minute)..."
	@./test/test_benchmark --benchmark_min_time=5s >/dev/null 2>&1 || true
	@echo "Step 3/3: Building optimized binary..."
	$(MAKE) clean
	$(MAKE) all \
		CCFLAGS="$(CCFLAGS) -fprofile-use" \
		CXXFLAGS="$(CXXFLAGS) -fprofile-use" \
		LDFLAGS="$(LDFLAGS) -fprofile-use"
	@echo "=== PGO build complete! ==="
	@echo "Binary 'omnomnum' is now optimized with PGO (~8% faster on average)"
	@echo "Run 'make pgo-clean' to remove profile data files"

pgo-clean:
	@echo "Removing PGO profile data..."
	@rm -f *.gcda test/*.gcda branchlut/*.gcda grisu2/*.gcda
	@echo "Profile data removed"
