/* Autogenerated from parser.c. Do not edit by hand. */
#include <stdio.h>
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif
#define ParseTOKENTYPE  YYSTYPE
#define ParseARG_PDECL , ParserState *state
void Parse(void *yyp,int yymajor,ParseTOKENTYPE yyminor ParseARG_PDECL);
void ParseReset(void *p);
#if defined(YYTRACKMAXSTACKDEPTH)
int ParseStackPeak(void *p);
#endif
void ParseFree(void *p,void(*freeProc)(void *));
void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE));
#if !defined(NDEBUG)
void ParseTrace(FILE *TraceFILE,char *zTracePrompt);
#endif
#define ParseARG_STORE yypParser->state  = state;
#define ParseARG_FETCH  ParserState *state  = yypParser->state;
#define ParseARG_SDECL  ParserState *state ;
#ifndef ParseCTX_SDECL
#define ParseCTX_SDECL
#endif
#ifndef ParseCTX_PDECL
#define ParseCTX_PDECL
#endif
#ifndef ParseCTX_PARAM
#define ParseCTX_PARAM
#endif
#ifndef ParseCTX_FETCH
#define ParseCTX_FETCH
#endif
#ifndef ParseCTX_STORE
#define ParseCTX_STORE
#endif
#define TOKEN_NEGATIVE                        1
#define TOKEN_AND_A                           2
#define TOKEN_QUARTER                         3
#define TOKEN_HALF                            4
#define TOKEN_QUARTERS                        5
#define TOKEN_ONE                             6
#define TOKEN_A                               7
#define TOKEN_HALVES                          8
#define TOKEN_FRACTION                        9
#define TOKEN_AND                            10
#define TOKEN_AN                             11
#define TOKEN_ZERO_WHOLE_NUMBER              12
#define TOKEN_WHOLE_NUMBER                   13
#define TOKEN_DECIMAL                        14
#define TOKEN_ZERO                           15
#define TOKEN_TRILLION                       16
#define TOKEN_TRILLIONTH                     17
#define TOKEN_TRILLIONTHS                    18
#define TOKEN_BILLION                        19
#define TOKEN_BILLIONTH                      20
#define TOKEN_BILLIONTHS                     21
#define TOKEN_MILLION                        22
#define TOKEN_MILLIONTH                      23
#define TOKEN_MILLIONTHS                     24
#define TOKEN_THOUSAND                       25
#define TOKEN_THOUSANDTH                     26
#define TOKEN_THOUSANDTHS                    27
#define TOKEN_HUNDRED                        28
#define TOKEN_HUNDREDTH                      29
#define TOKEN_HUNDREDTHS                     30
#define TOKEN_TWO                            31
#define TOKEN_THREE                          32
#define TOKEN_FOUR                           33
#define TOKEN_FIVE                           34
#define TOKEN_SIX                            35
#define TOKEN_SEVEN                          36
#define TOKEN_EIGHT                          37
#define TOKEN_NINE                           38
#define TOKEN_TEN                            39
#define TOKEN_ELEVEN                         40
#define TOKEN_TWELVE                         41
#define TOKEN_THIRTEEN                       42
#define TOKEN_FOURTEEN                       43
#define TOKEN_FIFTEEN                        44
#define TOKEN_SIXTEEN                        45
#define TOKEN_SEVENTEEN                      46
#define TOKEN_EIGHTEEN                       47
#define TOKEN_NINETEEN                       48
#define TOKEN_TWENTY                         49
#define TOKEN_THIRTY                         50
#define TOKEN_FORTY                          51
#define TOKEN_FIFTY                          52
#define TOKEN_SIXTY                          53
#define TOKEN_SEVENTY                        54
#define TOKEN_EIGHTY                         55
#define TOKEN_NINETY                         56
#define TOKEN_FIRST                          57
#define TOKEN_SECOND                         58
#define TOKEN_THIRD                          59
#define TOKEN_FOURTH                         60
#define TOKEN_FIFTH                          61
#define TOKEN_SIXTH                          62
#define TOKEN_SEVENTH                        63
#define TOKEN_EIGHTH                         64
#define TOKEN_NINTH                          65
#define TOKEN_TENTH                          66
#define TOKEN_ELEVENTH                       67
#define TOKEN_TWELFTH                        68
#define TOKEN_THIRTEENTH                     69
#define TOKEN_FOURTEENTH                     70
#define TOKEN_FIFTEENTH                      71
#define TOKEN_SIXTEENTH                      72
#define TOKEN_SEVENTEENTH                    73
#define TOKEN_EIGHTEENTH                     74
#define TOKEN_NINETEENTH                     75
#define TOKEN_TWENTIETH                      76
#define TOKEN_THIRTIETH                      77
#define TOKEN_FOURTIETH                      78
#define TOKEN_FIFTIETH                       79
#define TOKEN_SIXTIETH                       80
#define TOKEN_SEVENTIETH                     81
#define TOKEN_EIGHTIETH                      82
#define TOKEN_NINETIETH                      83
#define TOKEN_FIRSTS                         84
#define TOKEN_SECONDS                        85
#define TOKEN_THIRDS                         86
#define TOKEN_FOURTHS                        87
#define TOKEN_FIFTHS                         88
#define TOKEN_SIXTHS                         89
#define TOKEN_SEVENTHS                       90
#define TOKEN_EIGHTHS                        91
#define TOKEN_NINTHS                         92
#define TOKEN_TENTHS                         93
#define TOKEN_ELEVENTHS                      94
#define TOKEN_TWELFTHS                       95
#define TOKEN_THIRTEENTHS                    96
#define TOKEN_FOURTEENTHS                    97
#define TOKEN_FIFTEENTHS                     98
#define TOKEN_SIXTEENTHS                     99
#define TOKEN_SEVENTEENTHS                   100
#define TOKEN_EIGHTEENTHS                    101
#define TOKEN_NINETEENTHS                    102
#define TOKEN_TWENTIETHS                     103
#define TOKEN_THIRTIETHS                     104
#define TOKEN_FOURTIETHS                     105
#define TOKEN_FIFTIETHS                      106
#define TOKEN_SIXTIETHS                      107
#define TOKEN_SEVENTIETHS                    108
#define TOKEN_EIGHTIETHS                     109
#define TOKEN_NINETIETHS                     110
#define INTERFACE 0
