/* Autogenerated from parser.c. Do not edit by hand. */
#include <stdio.h>
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif
#define ParseTOKENTYPE  YYSTYPE
#define ParseARG_PDECL , ParserState *state
void Parse(void *yyp,int yymajor,ParseTOKENTYPE yyminor ParseARG_PDECL);
void ParseReset(void *p);
#if defined(YYTRACKMAXSTACKDEPTH)
int ParseStackPeak(void *p);
#endif
void ParseFree(void *p,void(*freeProc)(void *));
void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE));
#if !defined(NDEBUG)
void ParseTrace(FILE *TraceFILE,char *zTracePrompt);
#endif
#define ParseARG_STORE yypParser->state  = state;
#define ParseARG_FETCH  ParserState *state  = yypParser->state;
#define ParseARG_SDECL  ParserState *state ;
#ifndef ParseCTX_SDECL
#define ParseCTX_SDECL
#endif
#ifndef ParseCTX_PDECL
#define ParseCTX_PDECL
#endif
#ifndef ParseCTX_PARAM
#define ParseCTX_PARAM
#endif
#ifndef ParseCTX_FETCH
#define ParseCTX_FETCH
#endif
#ifndef ParseCTX_STORE
#define ParseCTX_STORE
#endif
#define TOKEN_NEGATIVE                        1
#define TOKEN_MINUS                           2
#define TOKEN_AND_A                           3
#define TOKEN_QUARTER                         4
#define TOKEN_HALF                            5
#define TOKEN_AND                             6
#define TOKEN_A                               7
#define TOKEN_QUARTERS                        8
#define TOKEN_ONE                             9
#define TOKEN_HALVES                         10
#define TOKEN_HUNDREDTH                      11
#define TOKEN_HUNDREDTHS                     12
#define TOKEN_FRACTION                       13
#define TOKEN_AN                             14
#define TOKEN_ZERO_WHOLE_NUMBER              15
#define TOKEN_WHOLE_NUMBER                   16
#define TOKEN_DECIMAL                        17
#define TOKEN_ZERO                           18
#define TOKEN_QUADRILLION                    19
#define TOKEN_QUADRILLIONTH                  20
#define TOKEN_QUADRILLIONTHS                 21
#define TOKEN_TRILLION                       22
#define TOKEN_TRILLIONTH                     23
#define TOKEN_TRILLIONTHS                    24
#define TOKEN_BILLION                        25
#define TOKEN_BILLIONTH                      26
#define TOKEN_BILLIONTHS                     27
#define TOKEN_MILLION                        28
#define TOKEN_MILLIONTH                      29
#define TOKEN_MILLIONTHS                     30
#define TOKEN_THOUSAND                       31
#define TOKEN_THOUSANDTH                     32
#define TOKEN_THOUSANDTHS                    33
#define TOKEN_HUNDRED                        34
#define TOKEN_TWO                            35
#define TOKEN_THREE                          36
#define TOKEN_FOUR                           37
#define TOKEN_FIVE                           38
#define TOKEN_SIX                            39
#define TOKEN_SEVEN                          40
#define TOKEN_EIGHT                          41
#define TOKEN_NINE                           42
#define TOKEN_TEN                            43
#define TOKEN_ELEVEN                         44
#define TOKEN_TWELVE                         45
#define TOKEN_THIRTEEN                       46
#define TOKEN_FOURTEEN                       47
#define TOKEN_FIFTEEN                        48
#define TOKEN_SIXTEEN                        49
#define TOKEN_SEVENTEEN                      50
#define TOKEN_EIGHTEEN                       51
#define TOKEN_NINETEEN                       52
#define TOKEN_TWENTY                         53
#define TOKEN_THIRTY                         54
#define TOKEN_FORTY                          55
#define TOKEN_FIFTY                          56
#define TOKEN_SIXTY                          57
#define TOKEN_SEVENTY                        58
#define TOKEN_EIGHTY                         59
#define TOKEN_NINETY                         60
#define TOKEN_FIRST                          61
#define TOKEN_SECOND                         62
#define TOKEN_THIRD                          63
#define TOKEN_FOURTH                         64
#define TOKEN_FIFTH                          65
#define TOKEN_SIXTH                          66
#define TOKEN_SEVENTH                        67
#define TOKEN_EIGHTH                         68
#define TOKEN_NINTH                          69
#define TOKEN_TENTH                          70
#define TOKEN_ELEVENTH                       71
#define TOKEN_TWELFTH                        72
#define TOKEN_THIRTEENTH                     73
#define TOKEN_FOURTEENTH                     74
#define TOKEN_FIFTEENTH                      75
#define TOKEN_SIXTEENTH                      76
#define TOKEN_SEVENTEENTH                    77
#define TOKEN_EIGHTEENTH                     78
#define TOKEN_NINETEENTH                     79
#define TOKEN_TWENTIETH                      80
#define TOKEN_THIRTIETH                      81
#define TOKEN_FOURTIETH                      82
#define TOKEN_FIFTIETH                       83
#define TOKEN_SIXTIETH                       84
#define TOKEN_SEVENTIETH                     85
#define TOKEN_EIGHTIETH                      86
#define TOKEN_NINETIETH                      87
#define TOKEN_FIRSTS                         88
#define TOKEN_SECONDS                        89
#define TOKEN_THIRDS                         90
#define TOKEN_FOURTHS                        91
#define TOKEN_FIFTHS                         92
#define TOKEN_SIXTHS                         93
#define TOKEN_SEVENTHS                       94
#define TOKEN_EIGHTHS                        95
#define TOKEN_NINTHS                         96
#define TOKEN_TENTHS                         97
#define TOKEN_ELEVENTHS                      98
#define TOKEN_TWELFTHS                       99
#define TOKEN_THIRTEENTHS                    100
#define TOKEN_FOURTEENTHS                    101
#define TOKEN_FIFTEENTHS                     102
#define TOKEN_SIXTEENTHS                     103
#define TOKEN_SEVENTEENTHS                   104
#define TOKEN_EIGHTEENTHS                    105
#define TOKEN_NINETEENTHS                    106
#define TOKEN_TWENTIETHS                     107
#define TOKEN_THIRTIETHS                     108
#define TOKEN_FOURTIETHS                     109
#define TOKEN_FIFTIETHS                      110
#define TOKEN_SIXTIETHS                      111
#define TOKEN_SEVENTIETHS                    112
#define TOKEN_EIGHTIETHS                     113
#define TOKEN_NINETIETHS                     114
#define INTERFACE 0
