/* Autogenerated from parser.c. Do not edit by hand. */
#include <stdio.h>
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif
#define ParseTOKENTYPE  YYSTYPE
#define ParseARG_PDECL , ParserState *state
void Parse(void *yyp,int yymajor,ParseTOKENTYPE yyminor ParseARG_PDECL);
void ParseReset(void *p);
#if defined(YYTRACKMAXSTACKDEPTH)
int ParseStackPeak(void *p);
#endif
void ParseFree(void *p,void(*freeProc)(void *));
void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE));
#if !defined(NDEBUG)
void ParseTrace(FILE *TraceFILE,char *zTracePrompt);
#endif
#define ParseARG_STORE yypParser->state  = state;
#define ParseARG_FETCH  ParserState *state  = yypParser->state;
#define ParseARG_SDECL  ParserState *state ;
#ifndef ParseCTX_SDECL
#define ParseCTX_SDECL
#endif
#ifndef ParseCTX_PDECL
#define ParseCTX_PDECL
#endif
#ifndef ParseCTX_PARAM
#define ParseCTX_PARAM
#endif
#ifndef ParseCTX_FETCH
#define ParseCTX_FETCH
#endif
#ifndef ParseCTX_STORE
#define ParseCTX_STORE
#endif
#define TOKEN_NEGATIVE                        1
#define TOKEN_AND_A                           2
#define TOKEN_QUARTER                         3
#define TOKEN_HALF                            4
#define TOKEN_AND                             5
#define TOKEN_A                               6
#define TOKEN_QUARTERS                        7
#define TOKEN_ONE                             8
#define TOKEN_HALVES                          9
#define TOKEN_HUNDREDTH                      10
#define TOKEN_HUNDREDTHS                     11
#define TOKEN_FRACTION                       12
#define TOKEN_AN                             13
#define TOKEN_ZERO_WHOLE_NUMBER              14
#define TOKEN_WHOLE_NUMBER                   15
#define TOKEN_DECIMAL                        16
#define TOKEN_ZERO                           17
#define TOKEN_QUADRILLION                    18
#define TOKEN_QUADRILLIONTH                  19
#define TOKEN_QUADRILLIONTHS                 20
#define TOKEN_TRILLION                       21
#define TOKEN_TRILLIONTH                     22
#define TOKEN_TRILLIONTHS                    23
#define TOKEN_BILLION                        24
#define TOKEN_BILLIONTH                      25
#define TOKEN_BILLIONTHS                     26
#define TOKEN_MILLION                        27
#define TOKEN_MILLIONTH                      28
#define TOKEN_MILLIONTHS                     29
#define TOKEN_THOUSAND                       30
#define TOKEN_THOUSANDTH                     31
#define TOKEN_THOUSANDTHS                    32
#define TOKEN_HUNDRED                        33
#define TOKEN_TWO                            34
#define TOKEN_THREE                          35
#define TOKEN_FOUR                           36
#define TOKEN_FIVE                           37
#define TOKEN_SIX                            38
#define TOKEN_SEVEN                          39
#define TOKEN_EIGHT                          40
#define TOKEN_NINE                           41
#define TOKEN_TEN                            42
#define TOKEN_ELEVEN                         43
#define TOKEN_TWELVE                         44
#define TOKEN_THIRTEEN                       45
#define TOKEN_FOURTEEN                       46
#define TOKEN_FIFTEEN                        47
#define TOKEN_SIXTEEN                        48
#define TOKEN_SEVENTEEN                      49
#define TOKEN_EIGHTEEN                       50
#define TOKEN_NINETEEN                       51
#define TOKEN_TWENTY                         52
#define TOKEN_THIRTY                         53
#define TOKEN_FORTY                          54
#define TOKEN_FIFTY                          55
#define TOKEN_SIXTY                          56
#define TOKEN_SEVENTY                        57
#define TOKEN_EIGHTY                         58
#define TOKEN_NINETY                         59
#define TOKEN_FIRST                          60
#define TOKEN_SECOND                         61
#define TOKEN_THIRD                          62
#define TOKEN_FOURTH                         63
#define TOKEN_FIFTH                          64
#define TOKEN_SIXTH                          65
#define TOKEN_SEVENTH                        66
#define TOKEN_EIGHTH                         67
#define TOKEN_NINTH                          68
#define TOKEN_TENTH                          69
#define TOKEN_ELEVENTH                       70
#define TOKEN_TWELFTH                        71
#define TOKEN_THIRTEENTH                     72
#define TOKEN_FOURTEENTH                     73
#define TOKEN_FIFTEENTH                      74
#define TOKEN_SIXTEENTH                      75
#define TOKEN_SEVENTEENTH                    76
#define TOKEN_EIGHTEENTH                     77
#define TOKEN_NINETEENTH                     78
#define TOKEN_TWENTIETH                      79
#define TOKEN_THIRTIETH                      80
#define TOKEN_FOURTIETH                      81
#define TOKEN_FIFTIETH                       82
#define TOKEN_SIXTIETH                       83
#define TOKEN_SEVENTIETH                     84
#define TOKEN_EIGHTIETH                      85
#define TOKEN_NINETIETH                      86
#define TOKEN_FIRSTS                         87
#define TOKEN_SECONDS                        88
#define TOKEN_THIRDS                         89
#define TOKEN_FOURTHS                        90
#define TOKEN_FIFTHS                         91
#define TOKEN_SIXTHS                         92
#define TOKEN_SEVENTHS                       93
#define TOKEN_EIGHTHS                        94
#define TOKEN_NINTHS                         95
#define TOKEN_TENTHS                         96
#define TOKEN_ELEVENTHS                      97
#define TOKEN_TWELFTHS                       98
#define TOKEN_THIRTEENTHS                    99
#define TOKEN_FOURTEENTHS                    100
#define TOKEN_FIFTEENTHS                     101
#define TOKEN_SIXTEENTHS                     102
#define TOKEN_SEVENTEENTHS                   103
#define TOKEN_EIGHTEENTHS                    104
#define TOKEN_NINETEENTHS                    105
#define TOKEN_TWENTIETHS                     106
#define TOKEN_THIRTIETHS                     107
#define TOKEN_FOURTIETHS                     108
#define TOKEN_FIFTIETHS                      109
#define TOKEN_SIXTIETHS                      110
#define TOKEN_SEVENTIETHS                    111
#define TOKEN_EIGHTIETHS                     112
#define TOKEN_NINETIETHS                     113
#define INTERFACE 0
