/* Generated by re2c 0.16 on Fri Feb  3 08:00:43 2017 */
#line 1 "scanner.re"
/* OmNomNum 0.0.2 -- Gobbles up numbers in strings.
 *
 * Copyright (c) 2017, Jesse Buesking <jessebuesking at gmail dot com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *   * Redistributions of source code must retain the above copyright notice,
 *     this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *   * Neither the name of OmNomNum nor the names of its contributors may be used
 *     to endorse or promote products derived from this software without
 *     specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include "scanner.h"

#define TOKEN_SEPARATOR 10000
#define TOKEN_CHARACTERS 10001
#define TOKEN_ALL_OTHERS 10002

int omnomnum_scanner_start(ParserState *state, void *pParser, YYSTYPE *yylval, scanstate *ss) {
fast_path:
    ss->token = ss->cursor;
    
#line 44 "scanner.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\n':
	case '\f':
	case '\r':
	case ' ':	goto yy6;
	case '+':	goto yy9;
	case '-':	goto yy10;
	case '.':	goto yy12;
	case '0':	goto yy13;
	case '1':	goto yy14;
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy16;
	case 'A':
	case 'a':	goto yy18;
	case 'B':
	case 'b':	goto yy20;
	case 'C':
	case 'D':
	case 'G':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'P':
	case 'R':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'c':
	case 'd':
	case 'g':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'p':
	case 'r':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':	goto yy22;
	case 'E':
	case 'e':	goto yy23;
	case 'F':
	case 'f':	goto yy24;
	case 'H':
	case 'h':	goto yy25;
	case 'M':
	case 'm':	goto yy26;
	case 'N':
	case 'n':	goto yy27;
	case 'O':
	case 'o':	goto yy28;
	case 'Q':
	case 'q':	goto yy29;
	case 'S':
	case 's':	goto yy30;
	case 'T':
	case 't':	goto yy31;
	case 'Z':
	case 'z':	goto yy32;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
#line 465 "scanner.re"
	{
            if (ss->cursor >= ss->limit) {
                // at the end of the string, so return
                return 0;
            }

            // just at a null byte in the middle of the string, so continue
            goto fast_path;
        }
#line 135 "scanner.c"
yy4:
	++YYCURSOR;
yy5:
#line 493 "scanner.re"
	{
            if (state->is_parsing) {
                Parse(pParser, 0, *yylval, state);
                ParseReset(pParser);
                state->is_parsing = false;
            }

            state->last_token = TOKEN_ALL_OTHERS;
            goto fast_path;
        }
#line 150 "scanner.c"
yy6:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\f':
	case '\r':
	case ' ':
	case '-':	goto yy6;
	default:	goto yy8;
	}
yy8:
#line 253 "scanner.re"
	{
            if (!state->is_parsing) {
                // not parsing and we've found a character. gobble it and continue
                state->last_token = TOKEN_SEPARATOR;
                goto fast_path;
            }

            return TOKEN_SEPARATOR;
        }
#line 174 "scanner.c"
yy9:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '+':
	case '-':	goto yy33;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy36;
	default:	goto yy5;
	}
yy10:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\f':
	case '\r':
	case ' ':	goto yy6;
	case '+':	goto yy33;
	case '-':	goto yy10;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy36;
	default:	goto yy8;
	}
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy37;
	default:	goto yy5;
	}
yy13:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ' ':	goto yy40;
	case '\'':	goto yy41;
	case ',':	goto yy42;
	case '.':	goto yy43;
	case '/':	goto yy44;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy45;
	default:	goto yy5;
	}
yy14:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ' ':	goto yy40;
	case '\'':	goto yy41;
	case ',':	goto yy42;
	case '.':	goto yy43;
	case '/':	goto yy44;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy47;
	default:	goto yy15;
	}
yy15:
#line 83 "scanner.re"
	{ return TOKEN_ONE; }
#line 277 "scanner.c"
yy16:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ' ':	goto yy40;
	case '\'':	goto yy41;
	case ',':	goto yy42;
	case '.':	goto yy43;
	case '/':	goto yy44;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy47;
	default:	goto yy17;
	}
yy17:
#line 449 "scanner.re"
	{
            // turn string version of number into double
            sds string_value = sdsnewlen(ss->token, ss->cursor - ss->token);
            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_WHOLE_NUMBER;
        }
#line 309 "scanner.c"
yy18:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ' ':	goto yy48;
	case 'N':
	case 'n':	goto yy49;
	default:	goto yy19;
	}
yy19:
#line 75 "scanner.re"
	{ return TOKEN_A; }
#line 322 "scanner.c"
yy20:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':
	case 'i':	goto yy51;
	default:	goto yy21;
	}
yy21:
#line 475 "scanner.re"
	{
            if (state->is_parsing) {
                if (state->last_token != TOKEN_SEPARATOR) {
                    // number followed by character... e.g. "oneself"
                } else {
                    // finish whatever we had and reset
                    Parse(pParser, 0, *yylval, state);
                }

                ParseReset(pParser);
                state->is_parsing = false;
            }

            state->last_token = TOKEN_CHARACTERS;
            goto fast_path;
        }
#line 349 "scanner.c"
yy22:
	yych = *++YYCURSOR;
	goto yy21;
yy23:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':
	case 'i':	goto yy52;
	case 'L':
	case 'l':	goto yy53;
	default:	goto yy21;
	}
yy24:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':
	case 'i':	goto yy54;
	case 'O':
	case 'o':	goto yy55;
	default:	goto yy21;
	}
yy25:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'A':
	case 'a':	goto yy56;
	case 'U':
	case 'u':	goto yy57;
	default:	goto yy21;
	}
yy26:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':
	case 'i':	goto yy58;
	default:	goto yy21;
	}
yy27:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy59;
	case 'I':
	case 'i':	goto yy60;
	default:	goto yy21;
	}
yy28:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'N':
	case 'n':	goto yy61;
	default:	goto yy21;
	}
yy29:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'U':
	case 'u':	goto yy62;
	default:	goto yy21;
	}
yy30:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy63;
	case 'I':
	case 'i':	goto yy64;
	default:	goto yy21;
	}
yy31:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy65;
	case 'H':
	case 'h':	goto yy66;
	case 'R':
	case 'r':	goto yy67;
	case 'W':
	case 'w':	goto yy68;
	default:	goto yy21;
	}
yy32:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy69;
	default:	goto yy21;
	}
yy33:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy33;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy36;
	default:	goto yy35;
	}
yy35:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy8;
	case 2: 	goto yy15;
	case 3: 	goto yy17;
	case 4: 	goto yy19;
	case 5: 	goto yy21;
	case 6: 	goto yy46;
	case 7: 	goto yy87;
	case 8: 	goto yy106;
	case 9: 	goto yy108;
	case 10: 	goto yy142;
	case 11: 	goto yy150;
	case 12: 	goto yy171;
	case 13: 	goto yy39;
	case 14: 	goto yy78;
	case 15: 	goto yy190;
	case 16: 	goto yy215;
	case 17: 	goto yy261;
	case 18: 	goto yy321;
	case 19: 	goto yy330;
	case 20: 	goto yy340;
	case 21: 	goto yy347;
	case 22: 	goto yy355;
	case 23: 	goto yy357;
	case 24: 	goto yy376;
	case 25: 	goto yy389;
	case 26: 	goto yy392;
	case 27: 	goto yy403;
	case 28: 	goto yy413;
	case 29: 	goto yy420;
	case 30: 	goto yy432;
	case 31: 	goto yy435;
	case 32: 	goto yy437;
	case 33: 	goto yy445;
	case 34: 	goto yy447;
	case 35: 	goto yy449;
	case 36: 	goto yy474;
	case 37: 	goto yy489;
	case 38: 	goto yy495;
	default:	goto yy497;
	}
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy40;
	case '\'':	goto yy41;
	case ',':	goto yy42;
	case '.':	goto yy70;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy71;
	default:	goto yy35;
	}
yy37:
	++YYCURSOR;
	yych = *YYCURSOR;
yy38:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy37;
	default:	goto yy39;
	}
yy39:
#line 457 "scanner.re"
	{
            // turn string version of number into double
            sds string_value = sdsnewlen(ss->token, ss->cursor - ss->token);
            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_DECIMAL;
        }
#line 557 "scanner.c"
yy40:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy72;
	default:	goto yy35;
	}
yy41:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy73;
	default:	goto yy35;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy74;
	default:	goto yy35;
	}
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy75;
	default:	goto yy35;
	}
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy76;
	default:	goto yy35;
	}
yy45:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ' ':	goto yy40;
	case '\'':	goto yy41;
	case ',':	goto yy42;
	case '.':	goto yy43;
	case '/':	goto yy79;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy80;
	default:	goto yy46;
	}
yy46:
#line 441 "scanner.re"
	{
            // turn string version of number into double
            sds string_value = sdsnewlen(ss->token, ss->cursor - ss->token);
            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_ZERO_WHOLE_NUMBER;
        }
#line 666 "scanner.c"
yy47:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ' ':	goto yy40;
	case '\'':	goto yy41;
	case ',':	goto yy42;
	case '.':	goto yy43;
	case '/':	goto yy79;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy81;
	default:	goto yy17;
	}
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'B':
	case 'b':	goto yy82;
	case 'H':
	case 'h':	goto yy83;
	case 'M':
	case 'm':	goto yy84;
	case 'T':
	case 't':	goto yy85;
	default:	goto yy35;
	}
yy49:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'D':
	case 'd':	goto yy86;
	default:	goto yy50;
	}
yy50:
#line 76 "scanner.re"
	{ return TOKEN_AN; }
#line 711 "scanner.c"
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy88;
	default:	goto yy35;
	}
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy89;
	default:	goto yy35;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy90;
	default:	goto yy35;
	}
yy54:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy91;
	case 'R':
	case 'r':	goto yy92;
	case 'V':
	case 'v':	goto yy93;
	default:	goto yy35;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy94;
	case 'U':
	case 'u':	goto yy95;
	default:	goto yy35;
	}
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy96;
	default:	goto yy35;
	}
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy97;
	default:	goto yy35;
	}
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy98;
	default:	goto yy35;
	}
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy99;
	default:	goto yy35;
	}
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy100;
	default:	goto yy35;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy101;
	default:	goto yy35;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy102;
	default:	goto yy35;
	}
yy63:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy103;
	case 'V':
	case 'v':	goto yy104;
	default:	goto yy35;
	}
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'X':
	case 'x':	goto yy105;
	default:	goto yy35;
	}
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy107;
	default:	goto yy35;
	}
yy66:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy109;
	case 'O':
	case 'o':	goto yy110;
	case 'R':
	case 'r':	goto yy111;
	default:	goto yy35;
	}
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy112;
	default:	goto yy35;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy113;
	case 'O':
	case 'o':	goto yy114;
	default:	goto yy35;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy116;
	default:	goto yy35;
	}
yy70:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy117;
	default:	goto yy35;
	}
yy71:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy40;
	case '\'':	goto yy41;
	case ',':	goto yy42;
	case '.':	goto yy70;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy118;
	default:	goto yy35;
	}
yy72:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy119;
	default:	goto yy35;
	}
yy73:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy120;
	default:	goto yy35;
	}
yy74:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy121;
	default:	goto yy35;
	}
yy75:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy122;
	default:	goto yy39;
	}
yy76:
	++YYCURSOR;
	yych = *YYCURSOR;
yy77:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy76;
	default:	goto yy78;
	}
yy78:
#line 278 "scanner.re"
	{
            if (state->is_parsing) {
                if (state->last_token != TOKEN_SEPARATOR) {
                    // number followed by character... e.g. "oneself"
                } else {
                    // finish whatever we had and reset
                    Parse(pParser, 0, *yylval, state);
                }

                ParseReset(pParser);
                state->is_parsing = false;
            }

            state->last_token = TOKEN_CHARACTERS;
            goto fast_path;
        }
#line 991 "scanner.c"
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy123;
	default:	goto yy35;
	}
yy80:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ' ':	goto yy40;
	case '\'':	goto yy41;
	case ',':	goto yy124;
	case '.':	goto yy43;
	case '/':	goto yy79;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy125;
	default:	goto yy46;
	}
yy81:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ' ':	goto yy40;
	case '\'':	goto yy41;
	case ',':	goto yy124;
	case '.':	goto yy43;
	case '/':	goto yy79;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy126;
	default:	goto yy17;
	}
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy127;
	default:	goto yy35;
	}
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy128;
	default:	goto yy35;
	}
yy84:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy129;
	default:	goto yy35;
	}
yy85:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy130;
	case 'R':
	case 'r':	goto yy131;
	default:	goto yy35;
	}
yy86:
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ' ':	goto yy132;
	default:	goto yy87;
	}
yy87:
#line 77 "scanner.re"
	{ return TOKEN_AND; }
#line 1089 "scanner.c"
yy88:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy133;
	default:	goto yy35;
	}
yy89:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy134;
	default:	goto yy35;
	}
yy90:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'V':
	case 'v':	goto yy135;
	default:	goto yy35;
	}
yy91:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy136;
	default:	goto yy35;
	}
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy137;
	default:	goto yy35;
	}
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy138;
	default:	goto yy35;
	}
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy140;
	default:	goto yy35;
	}
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy141;
	default:	goto yy35;
	}
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy143;
	case 'V':
	case 'v':	goto yy145;
	default:	goto yy35;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy146;
	default:	goto yy35;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy147;
	default:	goto yy35;
	}
yy99:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy148;
	default:	goto yy35;
	}
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy149;
	case 'T':
	case 't':	goto yy151;
	default:	goto yy35;
	}
yy101:
	yych = *++YYCURSOR;
	goto yy15;
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy152;
	default:	goto yy35;
	}
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy153;
	default:	goto yy35;
	}
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy154;
	default:	goto yy35;
	}
yy105:
	yyaccept = 8;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy155;
	default:	goto yy106;
	}
yy106:
#line 88 "scanner.re"
	{ return TOKEN_SIX; }
#line 1220 "scanner.c"
yy107:
	yyaccept = 9;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy156;
	default:	goto yy108;
	}
yy108:
#line 92 "scanner.re"
	{ return TOKEN_TEN; }
#line 1232 "scanner.c"
yy109:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy157;
	default:	goto yy35;
	}
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy158;
	default:	goto yy35;
	}
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy159;
	default:	goto yy35;
	}
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy160;
	default:	goto yy35;
	}
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy161;
	case 'N':
	case 'n':	goto yy162;
	default:	goto yy35;
	}
yy114:
	++YYCURSOR;
#line 84 "scanner.re"
	{ return TOKEN_TWO; }
#line 1274 "scanner.c"
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy163;
	default:	goto yy35;
	}
yy117:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy165;
	default:	goto yy35;
	}
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy40;
	case '\'':	goto yy41;
	case ',':	goto yy124;
	case '.':	goto yy70;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy166;
	default:	goto yy35;
	}
yy119:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	default:	goto yy35;
	}
yy120:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy168;
	default:	goto yy35;
	}
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
	case ',':	goto yy169;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy170;
	default:	goto yy35;
	}
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy172;
	default:	goto yy39;
	}
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy173;
	default:	goto yy78;
	}
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy174;
	default:	goto yy35;
	}
yy125:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ',':	goto yy175;
	case '/':	goto yy79;
	default:	goto yy178;
	}
yy126:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ',':	goto yy175;
	case '/':	goto yy79;
	default:	goto yy180;
	}
yy127:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy181;
	default:	goto yy35;
	}
yy128:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy182;
	default:	goto yy35;
	}
yy129:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy183;
	default:	goto yy35;
	}
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy184;
	default:	goto yy35;
	}
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy185;
	default:	goto yy35;
	}
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy186;
	default:	goto yy35;
	}
yy133:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy188;
	default:	goto yy35;
	}
yy134:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy189;
	default:	goto yy35;
	}
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy191;
	default:	goto yy35;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy192;
	case 'H':
	case 'h':	goto yy193;
	case 'I':
	case 'i':	goto yy195;
	case 'Y':
	case 'y':	goto yy196;
	default:	goto yy35;
	}
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy198;
	default:	goto yy35;
	}
yy138:
	++YYCURSOR;
#line 87 "scanner.re"
	{ return TOKEN_FIVE; }
#line 1513 "scanner.c"
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy200;
	case 'Y':
	case 'y':	goto yy201;
	default:	goto yy35;
	}
yy141:
	yyaccept = 10;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy203;
	default:	goto yy142;
	}
yy142:
#line 86 "scanner.re"
	{ return TOKEN_FOUR; }
#line 1534 "scanner.c"
yy143:
	++YYCURSOR;
#line 190 "scanner.re"
	{ return TOKEN_HALF; }
#line 1539 "scanner.c"
yy145:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy204;
	default:	goto yy35;
	}
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy205;
	default:	goto yy35;
	}
yy147:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy206;
	default:	goto yy35;
	}
yy148:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy207;
	default:	goto yy35;
	}
yy149:
	yyaccept = 11;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy208;
	default:	goto yy150;
	}
yy150:
#line 91 "scanner.re"
	{ return TOKEN_NINE; }
#line 1579 "scanner.c"
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy209;
	case 'H':
	case 'h':	goto yy210;
	default:	goto yy35;
	}
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy212;
	default:	goto yy35;
	}
yy153:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy213;
	default:	goto yy35;
	}
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy214;
	default:	goto yy35;
	}
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy216;
	case 'H':
	case 'h':	goto yy217;
	case 'I':
	case 'i':	goto yy219;
	case 'Y':
	case 'y':	goto yy220;
	default:	goto yy35;
	}
yy156:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy222;
	default:	goto yy35;
	}
yy157:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy224;
	case 'T':
	case 't':	goto yy226;
	default:	goto yy35;
	}
yy158:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy227;
	default:	goto yy35;
	}
yy159:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy228;
	default:	goto yy35;
	}
yy160:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy230;
	default:	goto yy35;
	}
yy161:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy231;
	case 'V':
	case 'v':	goto yy232;
	default:	goto yy35;
	}
yy162:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy233;
	default:	goto yy35;
	}
yy163:
	++YYCURSOR;
#line 82 "scanner.re"
	{ return TOKEN_ZERO; }
#line 1680 "scanner.c"
yy165:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy234;
	default:	goto yy35;
	}
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
	case ',':	goto yy175;
	default:	goto yy35;
	}
yy167:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case ' ':	goto yy40;
	case ',':	goto yy235;
	case '.':	goto yy236;
	default:	goto yy35;
	}
yy168:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '\'':	goto yy41;
	case '.':	goto yy237;
	default:	goto yy35;
	}
yy169:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy238;
	default:	goto yy35;
	}
yy170:
	yyaccept = 12;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ',':	goto yy239;
	case '.':	goto yy240;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy241;
	case 0xC2:	goto yy242;
	default:	goto yy171;
	}
yy171:
#line 294 "scanner.re"
	{
            // create duplicate of string (to be modified inplace)
            size_t token_len = ss->cursor - ss->token;
            char* tmp = (char*)malloc(token_len + 1);
            strncpy(tmp, ss->token, token_len);
            tmp[token_len] = '\0';

            size_t len = remove_char_inplace(tmp, ss->cursor - ss->token, ',');

            // turn string version of number into double
            sds string_value = sdsnewlen(tmp, len);
            free(tmp);

            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_DECIMAL;
        }
#line 1775 "scanner.c"
yy172:
	yyaccept = 13;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ',':	goto yy243;
	case '.':	goto yy70;
	default:	goto yy38;
	}
yy173:
	yyaccept = 14;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '/':	goto yy244;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy245;
	default:	goto yy78;
	}
yy174:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy246;
	default:	goto yy35;
	}
yy175:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy247;
	default:	goto yy35;
	}
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy37;
	default:	goto yy35;
	}
yy177:
	yyaccept = 6;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
yy178:
	switch (yych) {
	case '.':	goto yy176;
	case '/':	goto yy44;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy177;
	default:	goto yy46;
	}
yy179:
	yyaccept = 3;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
yy180:
	switch (yych) {
	case '.':	goto yy176;
	case '/':	goto yy44;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy179;
	default:	goto yy17;
	}
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy248;
	default:	goto yy35;
	}
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy249;
	default:	goto yy35;
	}
yy183:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy250;
	default:	goto yy35;
	}
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy251;
	default:	goto yy35;
	}
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy252;
	default:	goto yy35;
	}
yy186:
	++YYCURSOR;
#line 78 "scanner.re"
	{ return TOKEN_AND_A; }
#line 1926 "scanner.c"
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy253;
	default:	goto yy35;
	}
yy189:
	yyaccept = 15;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy254;
	case 'H':
	case 'h':	goto yy255;
	case 'I':
	case 'i':	goto yy257;
	case 'Y':
	case 'y':	goto yy258;
	default:	goto yy190;
	}
yy190:
#line 90 "scanner.re"
	{ return TOKEN_EIGHT; }
#line 1951 "scanner.c"
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy260;
	default:	goto yy35;
	}
yy192:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy262;
	default:	goto yy35;
	}
yy193:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy263;
	default:	goto yy194;
	}
yy194:
#line 150 "scanner.re"
	{ return TOKEN_FIFTH; }
#line 1976 "scanner.c"
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy265;
	default:	goto yy35;
	}
yy196:
	++YYCURSOR;
#line 108 "scanner.re"
	{ return TOKEN_FIFTY; }
#line 1988 "scanner.c"
yy198:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy266;
	default:	goto yy199;
	}
yy199:
#line 125 "scanner.re"
	{ return TOKEN_FIRST; }
#line 1999 "scanner.c"
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy268;
	default:	goto yy35;
	}
yy201:
	++YYCURSOR;
#line 106 "scanner.re"
	{ return TOKEN_FORTY; }
#line 2011 "scanner.c"
yy203:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy269;
	case 'H':
	case 'h':	goto yy270;
	case 'I':
	case 'i':	goto yy272;
	case 'Y':
	case 'y':	goto yy273;
	default:	goto yy35;
	}
yy204:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy275;
	default:	goto yy35;
	}
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy277;
	default:	goto yy35;
	}
yy206:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy278;
	default:	goto yy35;
	}
yy207:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy279;
	default:	goto yy35;
	}
yy208:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy280;
	case 'H':
	case 'h':	goto yy281;
	case 'I':
	case 'i':	goto yy283;
	case 'Y':
	case 'y':	goto yy284;
	default:	goto yy35;
	}
yy209:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy286;
	default:	goto yy35;
	}
yy210:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy287;
	default:	goto yy211;
	}
yy211:
#line 155 "scanner.re"
	{ return TOKEN_NINTH; }
#line 2083 "scanner.c"
yy212:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy289;
	default:	goto yy35;
	}
yy213:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy290;
	default:	goto yy35;
	}
yy214:
	yyaccept = 16;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy292;
	default:	goto yy215;
	}
yy215:
#line 89 "scanner.re"
	{ return TOKEN_SEVEN; }
#line 2109 "scanner.c"
yy216:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy293;
	default:	goto yy35;
	}
yy217:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy294;
	default:	goto yy218;
	}
yy218:
#line 151 "scanner.re"
	{ return TOKEN_SIXTH; }
#line 2127 "scanner.c"
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy296;
	default:	goto yy35;
	}
yy220:
	++YYCURSOR;
#line 109 "scanner.re"
	{ return TOKEN_SIXTY; }
#line 2139 "scanner.c"
yy222:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy297;
	default:	goto yy223;
	}
yy223:
#line 157 "scanner.re"
	{ return TOKEN_TENTH; }
#line 2150 "scanner.c"
yy224:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy299;
	default:	goto yy225;
	}
yy225:
#line 148 "scanner.re"
	{ return TOKEN_THIRD; }
#line 2161 "scanner.c"
yy226:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy301;
	case 'I':
	case 'i':	goto yy302;
	case 'Y':
	case 'y':	goto yy303;
	default:	goto yy35;
	}
yy227:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy305;
	default:	goto yy35;
	}
yy228:
	++YYCURSOR;
#line 85 "scanner.re"
	{ return TOKEN_THREE; }
#line 2184 "scanner.c"
yy230:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy306;
	default:	goto yy35;
	}
yy231:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy307;
	default:	goto yy35;
	}
yy232:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy308;
	default:	goto yy35;
	}
yy233:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy310;
	case 'Y':
	case 'y':	goto yy311;
	default:	goto yy35;
	}
yy234:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case ',':	goto yy243;
	case '.':	goto yy70;
	default:	goto yy35;
	}
yy235:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy313;
	default:	goto yy35;
	}
yy236:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy316;
	default:	goto yy35;
	}
yy237:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy319;
	default:	goto yy35;
	}
yy238:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy322;
	default:	goto yy35;
	}
yy239:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy323;
	default:	goto yy35;
	}
yy240:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy324;
	default:	goto yy35;
	}
yy241:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case ',':	goto yy175;
	case '.':	goto yy326;
	default:	goto yy35;
	}
yy242:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0xB7:	goto yy327;
	default:	goto yy35;
	}
yy243:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy328;
	default:	goto yy35;
	}
yy244:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy331;
	default:	goto yy35;
	}
yy245:
	yyaccept = 14;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '/':	goto yy244;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy332;
	default:	goto yy78;
	}
yy246:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy170;
	default:	goto yy35;
	}
yy247:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy333;
	default:	goto yy35;
	}
yy248:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy334;
	default:	goto yy35;
	}
yy249:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy335;
	default:	goto yy35;
	}
yy250:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy336;
	default:	goto yy35;
	}
yy251:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy337;
	default:	goto yy35;
	}
yy252:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy338;
	default:	goto yy35;
	}
yy253:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy339;
	default:	goto yy35;
	}
yy254:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy341;
	default:	goto yy35;
	}
yy255:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy342;
	default:	goto yy256;
	}
yy256:
#line 153 "scanner.re"
	{ return TOKEN_EIGHTH; }
#line 2470 "scanner.c"
yy257:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy344;
	default:	goto yy35;
	}
yy258:
	++YYCURSOR;
#line 111 "scanner.re"
	{ return TOKEN_EIGHTY; }
#line 2482 "scanner.c"
yy260:
	yyaccept = 17;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy345;
	default:	goto yy261;
	}
yy261:
#line 93 "scanner.re"
	{ return TOKEN_ELEVEN; }
#line 2494 "scanner.c"
yy262:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy346;
	default:	goto yy35;
	}
yy263:
	++YYCURSOR;
#line 217 "scanner.re"
	{ return TOKEN_FIFTHS; }
#line 2506 "scanner.c"
yy265:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy348;
	default:	goto yy35;
	}
yy266:
	++YYCURSOR;
#line 192 "scanner.re"
	{ return TOKEN_FIRSTS; }
#line 2518 "scanner.c"
yy268:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy349;
	default:	goto yy35;
	}
yy269:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy350;
	default:	goto yy35;
	}
yy270:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy351;
	default:	goto yy271;
	}
yy271:
#line 149 "scanner.re"
	{ return TOKEN_FOURTH; }
#line 2543 "scanner.c"
yy272:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy353;
	default:	goto yy35;
	}
yy273:
	++YYCURSOR;
#line 107 "scanner.re"
	{ return TOKEN_FORTY; }
#line 2555 "scanner.c"
yy275:
	++YYCURSOR;
#line 251 "scanner.re"
	{ return TOKEN_HALVES; }
#line 2560 "scanner.c"
yy277:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy354;
	default:	goto yy35;
	}
yy278:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy356;
	default:	goto yy35;
	}
yy279:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'V':
	case 'v':	goto yy358;
	default:	goto yy35;
	}
yy280:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy359;
	default:	goto yy35;
	}
yy281:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy360;
	default:	goto yy282;
	}
yy282:
#line 154 "scanner.re"
	{ return TOKEN_NINTH; }
#line 2599 "scanner.c"
yy283:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy362;
	default:	goto yy35;
	}
yy284:
	++YYCURSOR;
#line 112 "scanner.re"
	{ return TOKEN_NINETY; }
#line 2611 "scanner.c"
yy286:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy363;
	default:	goto yy35;
	}
yy287:
	++YYCURSOR;
#line 222 "scanner.re"
	{ return TOKEN_NINTHS; }
#line 2623 "scanner.c"
yy289:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy365;
	default:	goto yy35;
	}
yy290:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy367;
	default:	goto yy291;
	}
yy291:
#line 126 "scanner.re"
	{
            if (!state->parse_second) {
                // dont' parse "second" by default. easiest way to do this is to
                // treat it as a character token
                if (state->is_parsing) {
                    if (state->last_token != TOKEN_SEPARATOR) {
                        // number followed by character... e.g. "oneself"
                    } else {
                        // finish whatever we had and reset
                        Parse(pParser, 0, *yylval, state);
                    }

                    ParseReset(pParser);
                    state->is_parsing = false;
                }

                state->last_token = TOKEN_CHARACTERS;
                goto fast_path;
            } else {
                return TOKEN_SECOND;
            }
        }
#line 2662 "scanner.c"
yy292:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy369;
	case 'H':
	case 'h':	goto yy370;
	case 'I':
	case 'i':	goto yy372;
	case 'Y':
	case 'y':	goto yy373;
	default:	goto yy35;
	}
yy293:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy375;
	default:	goto yy35;
	}
yy294:
	++YYCURSOR;
#line 218 "scanner.re"
	{ return TOKEN_SIXTHS; }
#line 2687 "scanner.c"
yy296:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy377;
	default:	goto yy35;
	}
yy297:
	++YYCURSOR;
#line 224 "scanner.re"
	{ return TOKEN_TENTHS; }
#line 2699 "scanner.c"
yy299:
	++YYCURSOR;
#line 215 "scanner.re"
	{ return TOKEN_THIRDS; }
#line 2704 "scanner.c"
yy301:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy378;
	default:	goto yy35;
	}
yy302:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy379;
	default:	goto yy35;
	}
yy303:
	++YYCURSOR;
#line 105 "scanner.re"
	{ return TOKEN_THIRTY; }
#line 2723 "scanner.c"
yy305:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy380;
	default:	goto yy35;
	}
yy306:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy381;
	default:	goto yy35;
	}
yy307:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy382;
	default:	goto yy35;
	}
yy308:
	++YYCURSOR;
#line 94 "scanner.re"
	{ return TOKEN_TWELVE; }
#line 2749 "scanner.c"
yy310:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy384;
	default:	goto yy35;
	}
yy311:
	++YYCURSOR;
#line 104 "scanner.re"
	{ return TOKEN_TWENTY; }
#line 2761 "scanner.c"
yy313:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy313;
	default:	goto yy315;
	}
yy315:
#line 330 "scanner.re"
	{
            // create duplicate of string (to be modified inplace)
            size_t token_len = ss->cursor - ss->token;
            char* tmp = (char*)malloc(token_len + 1);
            strncpy(tmp, ss->token, token_len);
            tmp[token_len] = '\0';

            size_t len = remove_char_inplace(tmp, ss->cursor - ss->token, ' ');
            replace_char_inplace(tmp, len, ',', '.');

            // turn string version of number into double
            sds string_value = sdsnewlen(tmp, len);
            free(tmp);

            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_DECIMAL;
        }
#line 2799 "scanner.c"
yy316:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy316;
	default:	goto yy318;
	}
yy318:
#line 312 "scanner.re"
	{
            // create duplicate of string (to be modified inplace)
            size_t token_len = ss->cursor - ss->token;
            char* tmp = (char*)malloc(token_len + 1);
            strncpy(tmp, ss->token, token_len);
            tmp[token_len] = '\0';

            size_t len = remove_char_inplace(tmp, ss->cursor - ss->token, ' ');

            // turn string version of number into double
            sds string_value = sdsnewlen(tmp, len);
            free(tmp);

            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_DECIMAL;
        }
#line 2836 "scanner.c"
yy319:
	yyaccept = 18;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '.':	goto yy237;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy319;
	default:	goto yy321;
	}
yy321:
#line 405 "scanner.re"
	{
            // create duplicate of string (to be modified inplace)
            size_t token_len = ss->cursor - ss->token;
            char* tmp = (char*)malloc(token_len + 1);
            strncpy(tmp, ss->token, token_len);
            tmp[token_len] = '\0';

            size_t len = remove_char_inplace(tmp, ss->cursor - ss->token, '\'');

            // turn string version of number into double
            sds string_value = sdsnewlen(tmp, len);
            free(tmp);

            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_DECIMAL;
        }
#line 2875 "scanner.c"
yy322:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case ',':	goto yy169;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy385;
	default:	goto yy35;
	}
yy323:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy386;
	default:	goto yy35;
	}
yy324:
	yyaccept = 12;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '.':	goto yy240;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy324;
	default:	goto yy171;
	}
yy326:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy387;
	default:	goto yy35;
	}
yy327:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy390;
	default:	goto yy35;
	}
yy328:
	yyaccept = 19;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case ',':	goto yy243;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy328;
	default:	goto yy330;
	}
yy330:
#line 368 "scanner.re"
	{
            // create duplicate of string (to be modified inplace)
            size_t token_len = ss->cursor - ss->token;
            char* tmp = (char*)malloc(token_len + 1);
            strncpy(tmp, ss->token, token_len);
            tmp[token_len] = '\0';

            size_t len = remove_char_inplace(tmp, ss->cursor - ss->token, '.');
            replace_char_inplace(tmp, len, ',', '.');

            // turn string version of number into double
            sds string_value = sdsnewlen(tmp, len);
            free(tmp);

            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_DECIMAL;
        }
#line 2998 "scanner.c"
yy331:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy393;
	default:	goto yy35;
	}
yy332:
	yyaccept = 14;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '/':	goto yy244;
	default:	goto yy77;
	}
yy333:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy395;
	default:	goto yy35;
	}
yy334:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy396;
	default:	goto yy35;
	}
yy335:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy397;
	default:	goto yy35;
	}
yy336:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy398;
	default:	goto yy35;
	}
yy337:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy399;
	default:	goto yy35;
	}
yy338:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy400;
	default:	goto yy35;
	}
yy339:
	yyaccept = 20;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy401;
	default:	goto yy340;
	}
yy340:
#line 121 "scanner.re"
	{ return TOKEN_BILLION; }
#line 3083 "scanner.c"
yy341:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy402;
	default:	goto yy35;
	}
yy342:
	++YYCURSOR;
#line 220 "scanner.re"
	{ return TOKEN_EIGHTHS; }
#line 3095 "scanner.c"
yy344:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy404;
	default:	goto yy35;
	}
yy345:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy405;
	default:	goto yy35;
	}
yy346:
	yyaccept = 21;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy407;
	default:	goto yy347;
	}
yy347:
#line 97 "scanner.re"
	{ return TOKEN_FIFTEEN; }
#line 3121 "scanner.c"
yy348:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy408;
	default:	goto yy35;
	}
yy349:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy410;
	default:	goto yy35;
	}
yy350:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy412;
	default:	goto yy35;
	}
yy351:
	++YYCURSOR;
#line 216 "scanner.re"
	{ return TOKEN_FOURTHS; }
#line 3147 "scanner.c"
yy353:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy414;
	default:	goto yy35;
	}
yy354:
	yyaccept = 22;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy415;
	default:	goto yy355;
	}
yy355:
#line 115 "scanner.re"
	{ return TOKEN_HUNDRED; }
#line 3166 "scanner.c"
yy356:
	yyaccept = 23;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy416;
	default:	goto yy357;
	}
yy357:
#line 119 "scanner.re"
	{ return TOKEN_MILLION; }
#line 3178 "scanner.c"
yy358:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy417;
	default:	goto yy35;
	}
yy359:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy419;
	default:	goto yy35;
	}
yy360:
	++YYCURSOR;
#line 221 "scanner.re"
	{ return TOKEN_NINTHS; }
#line 3197 "scanner.c"
yy362:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy421;
	default:	goto yy35;
	}
yy363:
	++YYCURSOR;
#line 102 "scanner.re"
	{ return TOKEN_NINETEEN; }
#line 3209 "scanner.c"
yy365:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy422;
	default:	goto yy366;
	}
yy366:
#line 189 "scanner.re"
	{ return TOKEN_QUARTER; }
#line 3220 "scanner.c"
yy367:
	++YYCURSOR;
#line 193 "scanner.re"
	{
            if (!state->parse_second) {
                // dont' parse "second" by default. easiest way to do this is to
                // treat it as a character token
                if (state->is_parsing) {
                    if (state->last_token != TOKEN_SEPARATOR) {
                        // number followed by character... e.g. "oneself"
                    } else {
                        // finish whatever we had and reset
                        Parse(pParser, 0, *yylval, state);
                    }

                    ParseReset(pParser);
                    state->is_parsing = false;
                }

                state->last_token = TOKEN_CHARACTERS;
                goto fast_path;
            } else {
                return TOKEN_SECONDS;
            }
        }
#line 3246 "scanner.c"
yy369:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy424;
	default:	goto yy35;
	}
yy370:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy425;
	default:	goto yy371;
	}
yy371:
#line 152 "scanner.re"
	{ return TOKEN_SEVENTH; }
#line 3264 "scanner.c"
yy372:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy427;
	default:	goto yy35;
	}
yy373:
	++YYCURSOR;
#line 110 "scanner.re"
	{ return TOKEN_SEVENTY; }
#line 3276 "scanner.c"
yy375:
	yyaccept = 24;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy428;
	default:	goto yy376;
	}
yy376:
#line 98 "scanner.re"
	{ return TOKEN_SIXTEEN; }
#line 3288 "scanner.c"
yy377:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy429;
	default:	goto yy35;
	}
yy378:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy431;
	default:	goto yy35;
	}
yy379:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy433;
	default:	goto yy35;
	}
yy380:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy434;
	default:	goto yy35;
	}
yy381:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy436;
	default:	goto yy35;
	}
yy382:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy438;
	default:	goto yy383;
	}
yy383:
#line 159 "scanner.re"
	{ return TOKEN_TWELFTH; }
#line 3334 "scanner.c"
yy384:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy440;
	default:	goto yy35;
	}
yy385:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy441;
	default:	goto yy35;
	}
yy386:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy442;
	default:	goto yy35;
	}
yy387:
	yyaccept = 25;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '.':	goto yy326;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy387;
	default:	goto yy389;
	}
yy389:
#line 423 "scanner.re"
	{
            // create duplicate of string (to be modified inplace)
            size_t token_len = ss->cursor - ss->token;
            char* tmp = (char*)malloc(token_len + 1);
            strncpy(tmp, ss->token, token_len);
            tmp[token_len] = '\0';

            size_t len = remove_char_inplace(tmp, ss->cursor - ss->token, ',');

            // turn string version of number into double
            sds string_value = sdsnewlen(tmp, len);
            free(tmp);

            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_DECIMAL;
        }
#line 3402 "scanner.c"
yy390:
	yyaccept = 26;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy390;
	case 0xC2:	goto yy242;
	default:	goto yy392;
	}
yy392:
#line 349 "scanner.re"
	{
            // create duplicate of string (to be modified inplace)
            size_t token_len = ss->cursor - ss->token;
            char* tmp = (char*)malloc(token_len + 1);
            strncpy(tmp, ss->token, token_len);
            tmp[token_len] = '\0';

            size_t len = remove_char_inplace(tmp, ss->cursor - ss->token, ',');
            len = replace_two_byte_char_inplace((unsigned char*)tmp, len, (unsigned char*)"·", '.');

            // turn string version of number into double
            sds string_value = sdsnewlen(tmp, len);
            free(tmp);

            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_DECIMAL;
        }
#line 3442 "scanner.c"
yy393:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy443;
	default:	goto yy394;
	}
yy394:
#line 262 "scanner.re"
	{
            if (state->is_parsing) {
                if (state->last_token != TOKEN_SEPARATOR) {
                    // number followed by character... e.g. "oneself"
                } else {
                    // finish whatever we had and reset
                    Parse(pParser, 0, *yylval, state);
                }

                ParseReset(pParser);
                state->is_parsing = false;
            }

            state->last_token = TOKEN_CHARACTERS;
            goto fast_path;
        }
#line 3476 "scanner.c"
yy395:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy241;
	default:	goto yy35;
	}
yy396:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy444;
	default:	goto yy35;
	}
yy397:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy446;
	default:	goto yy35;
	}
yy398:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy448;
	default:	goto yy35;
	}
yy399:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy450;
	default:	goto yy35;
	}
yy400:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy451;
	default:	goto yy35;
	}
yy401:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy452;
	default:	goto yy35;
	}
yy402:
	yyaccept = 27;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy454;
	default:	goto yy403;
	}
yy403:
#line 100 "scanner.re"
	{ return TOKEN_EIGHTEEN; }
#line 3546 "scanner.c"
yy404:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy455;
	default:	goto yy35;
	}
yy405:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy457;
	default:	goto yy406;
	}
yy406:
#line 158 "scanner.re"
	{ return TOKEN_ELEVENTH; }
#line 3564 "scanner.c"
yy407:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy459;
	default:	goto yy35;
	}
yy408:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy461;
	default:	goto yy409;
	}
yy409:
#line 172 "scanner.re"
	{ return TOKEN_FIFTIETH; }
#line 3582 "scanner.c"
yy410:
	++YYCURSOR;
#line 170 "scanner.re"
	{ return TOKEN_FOURTIETH; }
#line 3587 "scanner.c"
yy412:
	yyaccept = 28;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy463;
	default:	goto yy413;
	}
yy413:
#line 96 "scanner.re"
	{ return TOKEN_FOURTEEN; }
#line 3599 "scanner.c"
yy414:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy464;
	default:	goto yy35;
	}
yy415:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy466;
	default:	goto yy35;
	}
yy416:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy468;
	default:	goto yy35;
	}
yy417:
	++YYCURSOR;
#line 80 "scanner.re"
	{ return TOKEN_NEGATIVE; }
#line 3625 "scanner.c"
yy419:
	yyaccept = 29;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy470;
	default:	goto yy420;
	}
yy420:
#line 101 "scanner.re"
	{ return TOKEN_NINETEEN; }
#line 3637 "scanner.c"
yy421:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy471;
	default:	goto yy35;
	}
yy422:
	++YYCURSOR;
#line 250 "scanner.re"
	{ return TOKEN_QUARTERS; }
#line 3649 "scanner.c"
yy424:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy473;
	default:	goto yy35;
	}
yy425:
	++YYCURSOR;
#line 219 "scanner.re"
	{ return TOKEN_SEVENTHS; }
#line 3661 "scanner.c"
yy427:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy475;
	default:	goto yy35;
	}
yy428:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy476;
	default:	goto yy35;
	}
yy429:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy478;
	default:	goto yy430;
	}
yy430:
#line 173 "scanner.re"
	{ return TOKEN_SIXTIETH; }
#line 3686 "scanner.c"
yy431:
	yyaccept = 30;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy480;
	default:	goto yy432;
	}
yy432:
#line 95 "scanner.re"
	{ return TOKEN_THIRTEEN; }
#line 3698 "scanner.c"
yy433:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy481;
	default:	goto yy35;
	}
yy434:
	yyaccept = 31;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy483;
	default:	goto yy435;
	}
yy435:
#line 117 "scanner.re"
	{ return TOKEN_THOUSAND; }
#line 3717 "scanner.c"
yy436:
	yyaccept = 32;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy484;
	default:	goto yy437;
	}
yy437:
#line 123 "scanner.re"
	{ return TOKEN_TRILLION; }
#line 3729 "scanner.c"
yy438:
	++YYCURSOR;
#line 226 "scanner.re"
	{ return TOKEN_TWELFTHS; }
#line 3734 "scanner.c"
yy440:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy485;
	default:	goto yy35;
	}
yy441:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy487;
	default:	goto yy35;
	}
yy442:
	yyaccept = 12;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case ',':	goto yy239;
	case '.':	goto yy240;
	case 0xC2:	goto yy242;
	default:	goto yy171;
	}
yy443:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy490;
	default:	goto yy394;
	}
yy444:
	yyaccept = 33;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy491;
	default:	goto yy445;
	}
yy445:
#line 120 "scanner.re"
	{ return TOKEN_BILLION; }
#line 3794 "scanner.c"
yy446:
	yyaccept = 34;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy492;
	default:	goto yy447;
	}
yy447:
#line 114 "scanner.re"
	{ return TOKEN_HUNDRED; }
#line 3806 "scanner.c"
yy448:
	yyaccept = 35;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy493;
	default:	goto yy449;
	}
yy449:
#line 118 "scanner.re"
	{ return TOKEN_MILLION; }
#line 3818 "scanner.c"
yy450:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy494;
	default:	goto yy35;
	}
yy451:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy496;
	default:	goto yy35;
	}
yy452:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy498;
	default:	goto yy453;
	}
yy453:
#line 185 "scanner.re"
	{ return TOKEN_BILLIONTH; }
#line 3843 "scanner.c"
yy454:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy500;
	default:	goto yy35;
	}
yy455:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy502;
	default:	goto yy456;
	}
yy456:
#line 175 "scanner.re"
	{ return TOKEN_EIGHTIETH; }
#line 3861 "scanner.c"
yy457:
	++YYCURSOR;
#line 225 "scanner.re"
	{ return TOKEN_ELEVENTHS; }
#line 3866 "scanner.c"
yy459:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy504;
	default:	goto yy460;
	}
yy460:
#line 162 "scanner.re"
	{ return TOKEN_FIFTEENTH; }
#line 3877 "scanner.c"
yy461:
	++YYCURSOR;
#line 238 "scanner.re"
	{ return TOKEN_FIFTIETHS; }
#line 3882 "scanner.c"
yy463:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy506;
	default:	goto yy35;
	}
yy464:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy508;
	default:	goto yy465;
	}
yy465:
#line 171 "scanner.re"
	{ return TOKEN_FOURTIETH; }
#line 3900 "scanner.c"
yy466:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy510;
	default:	goto yy467;
	}
yy467:
#line 179 "scanner.re"
	{ return TOKEN_HUNDREDTH; }
#line 3911 "scanner.c"
yy468:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy512;
	default:	goto yy469;
	}
yy469:
#line 183 "scanner.re"
	{ return TOKEN_MILLIONTH; }
#line 3922 "scanner.c"
yy470:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy514;
	default:	goto yy35;
	}
yy471:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy516;
	default:	goto yy472;
	}
yy472:
#line 176 "scanner.re"
	{ return TOKEN_NINETIETH; }
#line 3940 "scanner.c"
yy473:
	yyaccept = 36;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy518;
	default:	goto yy474;
	}
yy474:
#line 99 "scanner.re"
	{ return TOKEN_SEVENTEEN; }
#line 3952 "scanner.c"
yy475:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy519;
	default:	goto yy35;
	}
yy476:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy521;
	default:	goto yy477;
	}
yy477:
#line 163 "scanner.re"
	{ return TOKEN_SIXTEENTH; }
#line 3970 "scanner.c"
yy478:
	++YYCURSOR;
#line 239 "scanner.re"
	{ return TOKEN_SIXTIETHS; }
#line 3975 "scanner.c"
yy480:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy523;
	default:	goto yy35;
	}
yy481:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy525;
	default:	goto yy482;
	}
yy482:
#line 169 "scanner.re"
	{ return TOKEN_THIRTIETH; }
#line 3993 "scanner.c"
yy483:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy527;
	default:	goto yy35;
	}
yy484:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy529;
	default:	goto yy35;
	}
yy485:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy531;
	default:	goto yy486;
	}
yy486:
#line 168 "scanner.re"
	{ return TOKEN_TWENTIETH; }
#line 4018 "scanner.c"
yy487:
	yyaccept = 37;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '.':	goto yy441;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy487;
	default:	goto yy489;
	}
yy489:
#line 387 "scanner.re"
	{
            // create duplicate of string (to be modified inplace)
            size_t token_len = ss->cursor - ss->token;
            char* tmp = (char*)malloc(token_len + 1);
            strncpy(tmp, ss->token, token_len);
            tmp[token_len] = '\0';

            size_t len = remove_char_inplace(tmp, ss->cursor - ss->token, ',');

            // turn string version of number into double
            sds string_value = sdsnewlen(tmp, len);
            free(tmp);

            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_DECIMAL;
        }
#line 4057 "scanner.c"
yy490:
	yych = *++YYCURSOR;
	goto yy394;
yy491:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy533;
	default:	goto yy35;
	}
yy492:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy535;
	default:	goto yy35;
	}
yy493:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy537;
	default:	goto yy35;
	}
yy494:
	yyaccept = 38;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy539;
	default:	goto yy495;
	}
yy495:
#line 116 "scanner.re"
	{ return TOKEN_THOUSAND; }
#line 4093 "scanner.c"
yy496:
	yyaccept = 39;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy540;
	default:	goto yy497;
	}
yy497:
#line 122 "scanner.re"
	{ return TOKEN_TRILLION; }
#line 4105 "scanner.c"
yy498:
	++YYCURSOR;
#line 247 "scanner.re"
	{ return TOKEN_BILLIONTHS; }
#line 4110 "scanner.c"
yy500:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy541;
	default:	goto yy501;
	}
yy501:
#line 165 "scanner.re"
	{ return TOKEN_EIGHTEENTH; }
#line 4121 "scanner.c"
yy502:
	++YYCURSOR;
#line 241 "scanner.re"
	{ return TOKEN_EIGHTIETHS; }
#line 4126 "scanner.c"
yy504:
	++YYCURSOR;
#line 229 "scanner.re"
	{ return TOKEN_FIFTEENTHS; }
#line 4131 "scanner.c"
yy506:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy543;
	default:	goto yy507;
	}
yy507:
#line 161 "scanner.re"
	{ return TOKEN_FOURTEENTH; }
#line 4142 "scanner.c"
yy508:
	++YYCURSOR;
#line 237 "scanner.re"
	{ return TOKEN_FOURTIETHS; }
#line 4147 "scanner.c"
yy510:
	++YYCURSOR;
#line 244 "scanner.re"
	{ return TOKEN_HUNDREDTHS; }
#line 4152 "scanner.c"
yy512:
	++YYCURSOR;
#line 246 "scanner.re"
	{ return TOKEN_MILLIONTHS; }
#line 4157 "scanner.c"
yy514:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy545;
	default:	goto yy515;
	}
yy515:
#line 166 "scanner.re"
	{ return TOKEN_NINETEENTH; }
#line 4168 "scanner.c"
yy516:
	++YYCURSOR;
#line 242 "scanner.re"
	{ return TOKEN_NINETIETHS; }
#line 4173 "scanner.c"
yy518:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy547;
	default:	goto yy35;
	}
yy519:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy549;
	default:	goto yy520;
	}
yy520:
#line 174 "scanner.re"
	{ return TOKEN_SEVENTIETH; }
#line 4191 "scanner.c"
yy521:
	++YYCURSOR;
#line 230 "scanner.re"
	{ return TOKEN_SIXTEENTHS; }
#line 4196 "scanner.c"
yy523:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy551;
	default:	goto yy524;
	}
yy524:
#line 160 "scanner.re"
	{ return TOKEN_THIRTEENTH; }
#line 4207 "scanner.c"
yy525:
	++YYCURSOR;
#line 236 "scanner.re"
	{ return TOKEN_THIRTIETHS; }
#line 4212 "scanner.c"
yy527:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy553;
	default:	goto yy528;
	}
yy528:
#line 181 "scanner.re"
	{ return TOKEN_THOUSANDTH; }
#line 4223 "scanner.c"
yy529:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy555;
	default:	goto yy530;
	}
yy530:
#line 187 "scanner.re"
	{ return TOKEN_TRILLIONTH; }
#line 4234 "scanner.c"
yy531:
	++YYCURSOR;
#line 235 "scanner.re"
	{ return TOKEN_TWENTIETHS; }
#line 4239 "scanner.c"
yy533:
	++YYCURSOR;
#line 184 "scanner.re"
	{ return TOKEN_BILLIONTH; }
#line 4244 "scanner.c"
yy535:
	++YYCURSOR;
#line 178 "scanner.re"
	{ return TOKEN_HUNDREDTH; }
#line 4249 "scanner.c"
yy537:
	++YYCURSOR;
#line 182 "scanner.re"
	{ return TOKEN_MILLIONTH; }
#line 4254 "scanner.c"
yy539:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy557;
	default:	goto yy35;
	}
yy540:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy559;
	default:	goto yy35;
	}
yy541:
	++YYCURSOR;
#line 232 "scanner.re"
	{ return TOKEN_EIGHTEENTHS; }
#line 4273 "scanner.c"
yy543:
	++YYCURSOR;
#line 228 "scanner.re"
	{ return TOKEN_FOURTEENTHS; }
#line 4278 "scanner.c"
yy545:
	++YYCURSOR;
#line 233 "scanner.re"
	{ return TOKEN_NINETEENTHS; }
#line 4283 "scanner.c"
yy547:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'S':
	case 's':	goto yy561;
	default:	goto yy548;
	}
yy548:
#line 164 "scanner.re"
	{ return TOKEN_SEVENTEENTH; }
#line 4294 "scanner.c"
yy549:
	++YYCURSOR;
#line 240 "scanner.re"
	{ return TOKEN_SEVENTIETHS; }
#line 4299 "scanner.c"
yy551:
	++YYCURSOR;
#line 227 "scanner.re"
	{ return TOKEN_THIRTEENTHS; }
#line 4304 "scanner.c"
yy553:
	++YYCURSOR;
#line 245 "scanner.re"
	{ return TOKEN_THOUSANDTHS; }
#line 4309 "scanner.c"
yy555:
	++YYCURSOR;
#line 248 "scanner.re"
	{ return TOKEN_TRILLIONTHS; }
#line 4314 "scanner.c"
yy557:
	++YYCURSOR;
#line 180 "scanner.re"
	{ return TOKEN_THOUSANDTH; }
#line 4319 "scanner.c"
yy559:
	++YYCURSOR;
#line 186 "scanner.re"
	{ return TOKEN_TRILLIONTH; }
#line 4324 "scanner.c"
yy561:
	++YYCURSOR;
#line 231 "scanner.re"
	{ return TOKEN_SEVENTEENTHS; }
#line 4329 "scanner.c"
}
#line 503 "scanner.re"

}
