/* Generated by re2c 4.3 on Tue Nov  4 00:14:29 2025 */
#line 1 "scanner.re"
/* OmNomNum 0.0.2 -- Gobbles up numbers in strings.
 *
 * Copyright (c) 2017, Jesse Buesking <jessebuesking at gmail dot com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *   * Redistributions of source code must retain the above copyright notice,
 *     this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *   * Neither the name of OmNomNum nor the names of its contributors may be used
 *     to endorse or promote products derived from this software without
 *     specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include "scanner.h"
#include <string.h>

static int map_card_small(const char* s, size_t n, double* out) {
    if (n==3 && !strncmp(s,"one",3)) { *out=1; return 1; }
    if (n==3 && !strncmp(s,"two",3)) { *out=2; return 1; }
    if (n==5 && !strncmp(s,"three",5)) { *out=3; return 1; }
    if (n==4 && !strncmp(s,"four",4)) { *out=4; return 1; }
    if (n==4 && !strncmp(s,"five",4)) { *out=5; return 1; }
    if (n==3 && !strncmp(s,"six",3)) { *out=6; return 1; }
    if (n==5 && !strncmp(s,"seven",5)) { *out=7; return 1; }
    if (n==5 && !strncmp(s,"eight",5)) { *out=8; return 1; }
    if (n==4 && !strncmp(s,"nine",4)) { *out=9; return 1; }
    return 0;
}

static int map_denom_word(const char* s, size_t n, double* den) {
    if ((n==4 && !strncmp(s,"half",4)) || (n==6 && !strncmp(s,"halves",6))) { *den=2; return 1; }
    if (n==7 && !strncmp(s,"quarter",7)) { *den=4; return 1; }
    if (n==8 && !strncmp(s,"quarters",8)) { *den=4; return 1; }
    if (n==5 && !strncmp(s,"third",5)) { *den=3; return 1; }
    if (n==6 && !strncmp(s,"thirds",6)) { *den=3; return 1; }
    if (n==6 && !strncmp(s,"fourth",6)) { *den=4; return 1; }
    if (n==7 && !strncmp(s,"fourths",7)) { *den=4; return 1; }
    if (n==5 && !strncmp(s,"fifth",5)) { *den=5; return 1; }
    if (n==6 && !strncmp(s,"fifths",6)) { *den=5; return 1; }
    if (n==5 && !strncmp(s,"sixth",5)) { *den=6; return 1; }
    if (n==6 && !strncmp(s,"sixths",6)) { *den=6; return 1; }
    if (n==7 && !strncmp(s,"seventh",7)) { *den=7; return 1; }
    if (n==8 && !strncmp(s,"sevenths",8)) { *den=7; return 1; }
    if (n==6 && !strncmp(s,"eighth",6)) { *den=8; return 1; }
    if (n==7 && !strncmp(s,"eighths",7)) { *den=8; return 1; }
    if (n==5 && !strncmp(s,"ninth",5)) { *den=9; return 1; }
    if (n==6 && !strncmp(s,"ninths",6)) { *den=9; return 1; }
    return 0;
}

#define TOKEN_SEPARATOR 10000
#define TOKEN_CHARACTERS 10001
#define TOKEN_ALL_OTHERS 10002

int omnomnum_scanner_start(ParserState *state, void *pParser, YYSTYPE *yylval, scanstate *ss) {
fast_path:
    ss->token = ss->cursor;
    
#line 79 "scanner.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ': goto yy4;
		case '+': goto yy6;
		case '-': goto yy7;
		case '.': goto yy8;
		case '0': goto yy9;
		case '1': goto yy10;
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy12;
		case 'A':
		case 'a': goto yy14;
		case 'B':
		case 'b': goto yy16;
		case 'C':
		case 'D':
		case 'G':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'P':
		case 'R':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'c':
		case 'd':
		case 'g':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'p':
		case 'r':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y': goto yy18;
		case 'E':
		case 'e': goto yy19;
		case 'F':
		case 'f': goto yy20;
		case 'H':
		case 'h': goto yy21;
		case 'M':
		case 'm': goto yy22;
		case 'N':
		case 'n': goto yy23;
		case 'O':
		case 'o': goto yy24;
		case 'Q':
		case 'q': goto yy25;
		case 'S':
		case 's': goto yy26;
		case 'T':
		case 't': goto yy27;
		case 'Z':
		case 'z': goto yy28;
		default: goto yy2;
	}
yy1:
	++YYCURSOR;
#line 583 "scanner.re"
	{
            if (ss->cursor >= ss->limit) {
                // at the end of the string, so return
                return 0;
            }

            // just at a null byte in the middle of the string, so continue
            goto fast_path;
        }
#line 170 "scanner.c"
yy2:
	++YYCURSOR;
yy3:
#line 611 "scanner.re"
	{
            if (state->is_parsing) {
                Parse(pParser, 0, *yylval, state);
                ParseReset(pParser);
                state->is_parsing = false;
            }

            state->last_token = TOKEN_ALL_OTHERS;
            goto fast_path;
        }
#line 185 "scanner.c"
yy4:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '-': goto yy4;
		default: goto yy5;
	}
yy5:
#line 371 "scanner.re"
	{
            if (!state->is_parsing) {
                // not parsing and we've found a character. gobble it and continue
                state->last_token = TOKEN_SEPARATOR;
                goto fast_path;
            }

            return TOKEN_SEPARATOR;
        }
#line 208 "scanner.c"
yy6:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '+':
		case '-': goto yy29;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy31;
		default: goto yy3;
	}
yy7:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ': goto yy4;
		case '+': goto yy29;
		case '-': goto yy7;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy31;
		default: goto yy5;
	}
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy32;
		default: goto yy3;
	}
yy9:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case '-': goto yy35;
		case ' ': goto yy37;
		case '\'': goto yy38;
		case ',': goto yy39;
		case '.': goto yy40;
		case '/': goto yy41;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy42;
		default: goto yy3;
	}
yy10:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case '-': goto yy35;
		case ' ': goto yy37;
		case '\'': goto yy38;
		case ',': goto yy39;
		case '.': goto yy40;
		case '/': goto yy41;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy44;
		default: goto yy11;
	}
yy11:
#line 201 "scanner.re"
	{ return TOKEN_ONE; }
#line 320 "scanner.c"
yy12:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case '-': goto yy35;
		case ' ': goto yy37;
		case '\'': goto yy38;
		case ',': goto yy39;
		case '.': goto yy40;
		case '/': goto yy41;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy44;
		default: goto yy13;
	}
yy13:
#line 567 "scanner.re"
	{
            // turn string version of number into double
            sds string_value = sdsnewlen(ss->token, ss->cursor - ss->token);
            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_WHOLE_NUMBER;
        }
#line 357 "scanner.c"
yy14:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case ' ': goto yy45;
		case 'N':
		case 'n': goto yy46;
		default: goto yy15;
	}
yy15:
#line 193 "scanner.re"
	{ return TOKEN_A; }
#line 370 "scanner.c"
yy16:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'I':
		case 'i': goto yy48;
		default: goto yy17;
	}
yy17:
#line 593 "scanner.re"
	{
            if (state->is_parsing) {
                if (state->last_token != TOKEN_SEPARATOR) {
                    // number followed by character... e.g. "oneself"
                } else {
                    // finish whatever we had and reset
                    Parse(pParser, 0, *yylval, state);
                }

                ParseReset(pParser);
                state->is_parsing = false;
            }

            state->last_token = TOKEN_CHARACTERS;
            goto fast_path;
        }
#line 397 "scanner.c"
yy18:
	++YYCURSOR;
	goto yy17;
yy19:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'I':
		case 'i': goto yy49;
		case 'L':
		case 'l': goto yy50;
		default: goto yy17;
	}
yy20:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'I':
		case 'i': goto yy51;
		case 'O':
		case 'o': goto yy52;
		default: goto yy17;
	}
yy21:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'A':
		case 'a': goto yy53;
		case 'U':
		case 'u': goto yy54;
		default: goto yy17;
	}
yy22:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'I':
		case 'i': goto yy55;
		default: goto yy17;
	}
yy23:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'E':
		case 'e': goto yy56;
		case 'I':
		case 'i': goto yy57;
		default: goto yy17;
	}
yy24:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'N':
		case 'n': goto yy58;
		default: goto yy17;
	}
yy25:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'U':
		case 'u': goto yy59;
		default: goto yy17;
	}
yy26:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'E':
		case 'e': goto yy60;
		case 'I':
		case 'i': goto yy61;
		default: goto yy17;
	}
yy27:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'E':
		case 'e': goto yy62;
		case 'H':
		case 'h': goto yy63;
		case 'R':
		case 'r': goto yy64;
		case 'W':
		case 'w': goto yy65;
		default: goto yy17;
	}
yy28:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'E':
		case 'e': goto yy66;
		default: goto yy17;
	}
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
		case '+':
		case '-': goto yy29;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy31;
		default: goto yy30;
	}
yy30:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
		case 0: goto yy3;
		case 1: goto yy5;
		case 2: goto yy11;
		case 3: goto yy13;
		case 4: goto yy15;
		case 5: goto yy17;
		case 6: goto yy43;
		case 7: goto yy87;
		case 8: goto yy106;
		case 9: goto yy108;
		case 10: goto yy115;
		case 11: goto yy141;
		case 12: goto yy144;
		case 13: goto yy151;
		case 14: goto yy175;
		case 15: goto yy34;
		case 16: goto yy78;
		case 17: goto yy193;
		case 18: goto yy224;
		case 19: goto yy237;
		case 20: goto yy269;
		case 21: goto yy324;
		case 22: goto yy331;
		case 23: goto yy341;
		case 24: goto yy347;
		case 25: goto yy354;
		case 26: goto yy356;
		case 27: goto yy379;
		case 28: goto yy391;
		case 29: goto yy393;
		case 30: goto yy404;
		case 31: goto yy413;
		case 32: goto yy419;
		case 33: goto yy436;
		case 34: goto yy439;
		case 35: goto yy441;
		case 36: goto yy448;
		case 37: goto yy450;
		case 38: goto yy452;
		case 39: goto yy484;
		case 40: goto yy497;
		case 41: goto yy503;
		default: goto yy505;
	}
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
		case ' ': goto yy67;
		case '\'': goto yy38;
		case ',': goto yy39;
		case '.': goto yy68;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy69;
		default: goto yy30;
	}
yy32:
	yych = *++YYCURSOR;
yy33:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy32;
		default: goto yy34;
	}
yy34:
#line 575 "scanner.re"
	{
            // turn string version of number into double
            sds string_value = sdsnewlen(ss->token, ss->cursor - ss->token);
            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_DECIMAL;
        }
#line 606 "scanner.c"
yy35:
	yych = *++YYCURSOR;
yy36:
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '-': goto yy35;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy70;
		default: goto yy30;
	}
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy72;
		default: goto yy36;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy73;
		default: goto yy30;
	}
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy74;
		default: goto yy30;
	}
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy75;
		default: goto yy30;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy76;
		default: goto yy30;
	}
yy42:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case '-': goto yy35;
		case ' ': goto yy37;
		case '\'': goto yy38;
		case ',': goto yy39;
		case '.': goto yy40;
		case '/': goto yy79;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy80;
		default: goto yy43;
	}
yy43:
#line 559 "scanner.re"
	{
            // turn string version of number into double
            sds string_value = sdsnewlen(ss->token, ss->cursor - ss->token);
            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_ZERO_WHOLE_NUMBER;
        }
#line 740 "scanner.c"
yy44:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case '-': goto yy35;
		case ' ': goto yy37;
		case '\'': goto yy38;
		case ',': goto yy39;
		case '.': goto yy40;
		case '/': goto yy79;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy81;
		default: goto yy13;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'B':
		case 'b': goto yy82;
		case 'H':
		case 'h': goto yy83;
		case 'M':
		case 'm': goto yy84;
		case 'T':
		case 't': goto yy85;
		default: goto yy30;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'D':
		case 'd': goto yy86;
		default: goto yy47;
	}
yy47:
#line 194 "scanner.re"
	{ return TOKEN_AN; }
#line 790 "scanner.c"
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L':
		case 'l': goto yy88;
		default: goto yy30;
	}
yy49:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'G':
		case 'g': goto yy89;
		default: goto yy30;
	}
yy50:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy90;
		default: goto yy30;
	}
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'F':
		case 'f': goto yy91;
		case 'R':
		case 'r': goto yy92;
		case 'V':
		case 'v': goto yy93;
		default: goto yy30;
	}
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'R':
		case 'r': goto yy94;
		case 'U':
		case 'u': goto yy95;
		default: goto yy30;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L':
		case 'l': goto yy96;
		default: goto yy30;
	}
yy54:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy97;
		default: goto yy30;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L':
		case 'l': goto yy98;
		default: goto yy30;
	}
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'G':
		case 'g': goto yy99;
		default: goto yy30;
	}
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy100;
		default: goto yy30;
	}
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy101;
		default: goto yy30;
	}
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'A':
		case 'a': goto yy102;
		default: goto yy30;
	}
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'C':
		case 'c': goto yy103;
		case 'V':
		case 'v': goto yy104;
		default: goto yy30;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'X':
		case 'x': goto yy105;
		default: goto yy30;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy107;
		default: goto yy30;
	}
yy63:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy109;
		case 'O':
		case 'o': goto yy110;
		case 'R':
		case 'r': goto yy111;
		default: goto yy30;
	}
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy112;
		default: goto yy30;
	}
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy113;
		case 'O':
		case 'o': goto yy114;
		default: goto yy30;
	}
yy66:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'R':
		case 'r': goto yy116;
		default: goto yy30;
	}
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy117;
		default: goto yy30;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy118;
		default: goto yy30;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
		case ' ': goto yy67;
		case '\'': goto yy38;
		case ',': goto yy39;
		case '.': goto yy68;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy119;
		default: goto yy30;
	}
yy70:
	yych = *++YYCURSOR;
yy71:
	switch (yych) {
		case '/': goto yy120;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy70;
		default: goto yy30;
	}
yy72:
	yych = *++YYCURSOR;
	switch (yych) {
		case '/': goto yy120;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy121;
		default: goto yy30;
	}
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy122;
		default: goto yy30;
	}
yy74:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy123;
		default: goto yy30;
	}
yy75:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy124;
		default: goto yy34;
	}
yy76:
	yych = *++YYCURSOR;
yy77:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy76;
		default: goto yy78;
	}
yy78:
#line 396 "scanner.re"
	{
            if (state->is_parsing) {
                if (state->last_token != TOKEN_SEPARATOR) {
                    // number followed by character... e.g. "oneself"
                } else {
                    // finish whatever we had and reset
                    Parse(pParser, 0, *yylval, state);
                }

                ParseReset(pParser);
                state->is_parsing = false;
            }

            state->last_token = TOKEN_CHARACTERS;
            goto fast_path;
        }
#line 1099 "scanner.c"
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy125;
		default: goto yy30;
	}
yy80:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case '-': goto yy35;
		case ' ': goto yy37;
		case '\'': goto yy38;
		case ',': goto yy126;
		case '.': goto yy40;
		case '/': goto yy79;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy127;
		default: goto yy43;
	}
yy81:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case '-': goto yy35;
		case ' ': goto yy37;
		case '\'': goto yy38;
		case ',': goto yy126;
		case '.': goto yy40;
		case '/': goto yy79;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy128;
		default: goto yy13;
	}
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy129;
		default: goto yy30;
	}
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'U':
		case 'u': goto yy130;
		default: goto yy30;
	}
yy84:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy131;
		default: goto yy30;
	}
yy85:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy132;
		case 'R':
		case 'r': goto yy133;
		default: goto yy30;
	}
yy86:
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case ' ': goto yy134;
		default: goto yy87;
	}
yy87:
#line 195 "scanner.re"
	{ return TOKEN_AND; }
#line 1207 "scanner.c"
yy88:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L':
		case 'l': goto yy135;
		default: goto yy30;
	}
yy89:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy136;
		default: goto yy30;
	}
yy90:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'V':
		case 'v': goto yy137;
		default: goto yy30;
	}
yy91:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy138;
		default: goto yy30;
	}
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy139;
		default: goto yy30;
	}
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy140;
		default: goto yy30;
	}
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy142;
		default: goto yy30;
	}
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'R':
		case 'r': goto yy143;
		default: goto yy30;
	}
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'F':
		case 'f': goto yy145;
		case 'V':
		case 'v': goto yy146;
		default: goto yy30;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'D':
		case 'd': goto yy147;
		default: goto yy30;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L':
		case 'l': goto yy148;
		default: goto yy30;
	}
yy99:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'A':
		case 'a': goto yy149;
		default: goto yy30;
	}
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy150;
		case 'T':
		case 't': goto yy152;
		default: goto yy30;
	}
yy101:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '-': goto yy153;
		default: goto yy11;
	}
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'R':
		case 'r': goto yy154;
		default: goto yy30;
	}
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'O':
		case 'o': goto yy155;
		default: goto yy30;
	}
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy156;
		default: goto yy30;
	}
yy105:
	yyaccept = 8;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '-': goto yy153;
		case 'T':
		case 't': goto yy157;
		default: goto yy106;
	}
yy106:
#line 206 "scanner.re"
	{ return TOKEN_SIX; }
#line 1353 "scanner.c"
yy107:
	yyaccept = 9;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy158;
		default: goto yy108;
	}
yy108:
#line 210 "scanner.re"
	{ return TOKEN_TEN; }
#line 1365 "scanner.c"
yy109:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'R':
		case 'r': goto yy159;
		default: goto yy30;
	}
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'U':
		case 'u': goto yy160;
		default: goto yy30;
	}
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy161;
		default: goto yy30;
	}
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L':
		case 'l': goto yy162;
		default: goto yy30;
	}
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L':
		case 'l': goto yy163;
		case 'N':
		case 'n': goto yy164;
		default: goto yy30;
	}
yy114:
	yyaccept = 10;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '-': goto yy153;
		default: goto yy115;
	}
yy115:
#line 202 "scanner.re"
	{ return TOKEN_TWO; }
#line 1418 "scanner.c"
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'O':
		case 'o': goto yy165;
		default: goto yy30;
	}
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy166;
		default: goto yy30;
	}
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy167;
		default: goto yy30;
	}
yy119:
	yych = *++YYCURSOR;
	switch (yych) {
		case ' ': goto yy67;
		case '\'': goto yy38;
		case ',': goto yy126;
		case '.': goto yy68;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy168;
		default: goto yy30;
	}
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy169;
		default: goto yy30;
	}
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
		case '/': goto yy120;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy171;
		default: goto yy30;
	}
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy172;
		default: goto yy30;
	}
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
		case ',': goto yy173;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy174;
		default: goto yy30;
	}
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy176;
		default: goto yy34;
	}
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy177;
		default: goto yy78;
	}
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy178;
		default: goto yy30;
	}
yy127:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case ',': goto yy179;
		case '/': goto yy79;
		default: goto yy182;
	}
yy128:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case ',': goto yy179;
		case '/': goto yy79;
		default: goto yy184;
	}
yy129:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L':
		case 'l': goto yy185;
		default: goto yy30;
	}
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy186;
		default: goto yy30;
	}
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L':
		case 'l': goto yy187;
		default: goto yy30;
	}
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'O':
		case 'o': goto yy188;
		default: goto yy30;
	}
yy133:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy189;
		default: goto yy30;
	}
yy134:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'A':
		case 'a': goto yy190;
		default: goto yy30;
	}
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy191;
		default: goto yy30;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy192;
		default: goto yy30;
	}
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy194;
		default: goto yy30;
	}
yy138:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy195;
		case 'H':
		case 'h': goto yy196;
		case 'I':
		case 'i': goto yy198;
		case 'Y':
		case 'y': goto yy199;
		default: goto yy30;
	}
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy200;
		default: goto yy30;
	}
yy140:
	yyaccept = 11;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '-': goto yy153;
		default: goto yy141;
	}
yy141:
#line 205 "scanner.re"
	{ return TOKEN_FIVE; }
#line 1696 "scanner.c"
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy202;
		case 'Y':
		case 'y': goto yy203;
		default: goto yy30;
	}
yy143:
	yyaccept = 12;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '-': goto yy153;
		case 'T':
		case 't': goto yy204;
		default: goto yy144;
	}
yy144:
#line 204 "scanner.re"
	{ return TOKEN_FOUR; }
#line 1723 "scanner.c"
yy145:
	++YYCURSOR;
#line 308 "scanner.re"
	{ return TOKEN_HALF; }
#line 1728 "scanner.c"
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy205;
		default: goto yy30;
	}
yy147:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'R':
		case 'r': goto yy206;
		default: goto yy30;
	}
yy148:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy207;
		default: goto yy30;
	}
yy149:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy208;
		default: goto yy30;
	}
yy150:
	yyaccept = 13;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '-': goto yy153;
		case 'T':
		case 't': goto yy209;
		default: goto yy151;
	}
yy151:
#line 209 "scanner.re"
	{ return TOKEN_NINE; }
#line 1774 "scanner.c"
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy210;
		case 'H':
		case 'h': goto yy211;
		default: goto yy30;
	}
yy153:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '-': goto yy153;
		case 'A':
		case 'a': goto yy213;
		case 'E':
		case 'e': goto yy214;
		case 'F':
		case 'f': goto yy215;
		case 'H':
		case 'h': goto yy216;
		case 'N':
		case 'n': goto yy217;
		case 'Q':
		case 'q': goto yy218;
		case 'S':
		case 's': goto yy219;
		case 'T':
		case 't': goto yy220;
		default: goto yy30;
	}
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy221;
		default: goto yy30;
	}
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy222;
		default: goto yy30;
	}
yy156:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy223;
		default: goto yy30;
	}
yy157:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy225;
		case 'H':
		case 'h': goto yy226;
		case 'I':
		case 'i': goto yy228;
		case 'Y':
		case 'y': goto yy229;
		default: goto yy30;
	}
yy158:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy230;
		default: goto yy30;
	}
yy159:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'D':
		case 'd': goto yy232;
		case 'T':
		case 't': goto yy234;
		default: goto yy30;
	}
yy160:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy235;
		default: goto yy30;
	}
yy161:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy236;
		default: goto yy30;
	}
yy162:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L':
		case 'l': goto yy238;
		default: goto yy30;
	}
yy163:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'F':
		case 'f': goto yy239;
		case 'V':
		case 'v': goto yy240;
		default: goto yy30;
	}
yy164:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy241;
		default: goto yy30;
	}
yy165:
	++YYCURSOR;
#line 200 "scanner.re"
	{ return TOKEN_ZERO; }
#line 1902 "scanner.c"
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy242;
		default: goto yy30;
	}
yy167:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy243;
		default: goto yy30;
	}
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
		case ',': goto yy179;
		default: goto yy30;
	}
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy169;
		default: goto yy170;
	}
yy170:
#line 112 "scanner.re"
	{
            // determine numbers by scanning substring
            const char* s = ss->token;
            const char* e = ss->cursor;
            // parse whole
            const char* p = s;
            double whole=0; while (p<e && *p>='0' && *p<='9') { whole = whole*10 + (*p - '0'); p++; }
            while (p<e && (*p==' '||*p=='\t'||*p=='\r'||*p=='\n'||*p=='\f'||*p=='-')) p++;
            double num=0; while (p<e && *p>='0' && *p<='9') { num = num*10 + (*p - '0'); p++; }
            if (p<e && *p=='/') p++;
            double den=0; while (p<e && *p>='0' && *p<='9') { den = den*10 + (*p - '0'); p++; }
            #ifdef SCANNER_FRACTIONS
            (*yylval).is_frac = true; (*yylval).frac_num = whole*den + num; (*yylval).frac_denom = den; return TOKEN_FRACTION;
            #else
            if (state->is_parsing) {
                if (state->last_token != TOKEN_SEPARATOR) {
                } else {
                    Parse(pParser, 0, *yylval, state);
                }
                ParseReset(pParser);
                state->is_parsing = false;
            }
            state->last_token = TOKEN_CHARACTERS;
            goto fast_path;
            #endif
        }
#line 1982 "scanner.c"
yy171:
	yych = *++YYCURSOR;
	switch (yych) {
		case ' ': goto yy67;
		case ',': goto yy244;
		case '.': goto yy245;
		default: goto yy71;
	}
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\'': goto yy38;
		case '.': goto yy246;
		default: goto yy30;
	}
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy247;
		default: goto yy30;
	}
yy174:
	yyaccept = 14;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case ',': goto yy248;
		case '.': goto yy249;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy250;
		case 0xC2: goto yy251;
		default: goto yy175;
	}
yy175:
#line 412 "scanner.re"
	{
            // create duplicate of string (to be modified inplace)
            size_t token_len = ss->cursor - ss->token;
            char* tmp = (char*)malloc(token_len + 1);
            strncpy(tmp, ss->token, token_len);
            tmp[token_len] = '\0';

            size_t len = remove_char_inplace(tmp, ss->cursor - ss->token, ',');

            // turn string version of number into double
            sds string_value = sdsnewlen(tmp, len);
            free(tmp);

            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_DECIMAL;
        }
#line 2052 "scanner.c"
yy176:
	yyaccept = 15;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case ',': goto yy252;
		case '.': goto yy68;
		default: goto yy33;
	}
yy177:
	yyaccept = 16;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '/': goto yy253;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy254;
		default: goto yy78;
	}
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy255;
		default: goto yy30;
	}
yy179:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy256;
		default: goto yy30;
	}
yy180:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy32;
		default: goto yy30;
	}
yy181:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
yy182:
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '-': goto yy35;
		case '.': goto yy180;
		case '/': goto yy41;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy181;
		default: goto yy43;
	}
yy183:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
yy184:
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '-': goto yy35;
		case '.': goto yy180;
		case '/': goto yy41;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy183;
		default: goto yy13;
	}
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L':
		case 'l': goto yy257;
		default: goto yy30;
	}
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'D':
		case 'd': goto yy258;
		default: goto yy30;
	}
yy187:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L':
		case 'l': goto yy259;
		default: goto yy30;
	}
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'U':
		case 'u': goto yy260;
		default: goto yy30;
	}
yy189:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L':
		case 'l': goto yy261;
		default: goto yy30;
	}
yy190:
	++YYCURSOR;
#line 196 "scanner.re"
	{ return TOKEN_AND_A; }
#line 2212 "scanner.c"
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'O':
		case 'o': goto yy262;
		default: goto yy30;
	}
yy192:
	yyaccept = 17;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '-': goto yy153;
		case 'E':
		case 'e': goto yy263;
		case 'H':
		case 'h': goto yy264;
		case 'I':
		case 'i': goto yy266;
		case 'Y':
		case 'y': goto yy267;
		default: goto yy193;
	}
yy193:
#line 208 "scanner.re"
	{ return TOKEN_EIGHT; }
#line 2243 "scanner.c"
yy194:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy268;
		default: goto yy30;
	}
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy270;
		default: goto yy30;
	}
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy271;
		default: goto yy197;
	}
yy197:
#line 268 "scanner.re"
	{ return TOKEN_FIFTH; }
#line 2268 "scanner.c"
yy198:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy272;
		default: goto yy30;
	}
yy199:
	++YYCURSOR;
#line 226 "scanner.re"
	{ return TOKEN_FIFTY; }
#line 2280 "scanner.c"
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy273;
		default: goto yy201;
	}
yy201:
#line 243 "scanner.re"
	{ return TOKEN_FIRST; }
#line 2291 "scanner.c"
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy274;
		default: goto yy30;
	}
yy203:
	++YYCURSOR;
#line 224 "scanner.re"
	{ return TOKEN_FORTY; }
#line 2303 "scanner.c"
yy204:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy275;
		case 'H':
		case 'h': goto yy276;
		case 'I':
		case 'i': goto yy278;
		case 'Y':
		case 'y': goto yy279;
		default: goto yy30;
	}
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy280;
		default: goto yy30;
	}
yy206:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy281;
		default: goto yy30;
	}
yy207:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'O':
		case 'o': goto yy282;
		default: goto yy30;
	}
yy208:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy283;
		default: goto yy30;
	}
yy209:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy284;
		case 'H':
		case 'h': goto yy285;
		case 'I':
		case 'i': goto yy287;
		case 'Y':
		case 'y': goto yy288;
		default: goto yy30;
	}
yy210:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy289;
		default: goto yy30;
	}
yy211:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy290;
		default: goto yy212;
	}
yy212:
#line 273 "scanner.re"
	{ return TOKEN_NINTH; }
#line 2375 "scanner.c"
yy213:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy291;
		default: goto yy30;
	}
yy214:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy292;
		default: goto yy30;
	}
yy215:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy293;
		case 'O':
		case 'o': goto yy294;
		default: goto yy30;
	}
yy216:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'A':
		case 'a': goto yy295;
		default: goto yy30;
	}
yy217:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy296;
		default: goto yy30;
	}
yy218:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'U':
		case 'u': goto yy297;
		default: goto yy30;
	}
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy298;
		case 'I':
		case 'i': goto yy299;
		default: goto yy30;
	}
yy220:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy300;
		default: goto yy30;
	}
yy221:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy301;
		default: goto yy30;
	}
yy222:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'D':
		case 'd': goto yy302;
		default: goto yy30;
	}
yy223:
	yyaccept = 18;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '-': goto yy153;
		case 'T':
		case 't': goto yy304;
		default: goto yy224;
	}
yy224:
#line 207 "scanner.re"
	{ return TOKEN_SEVEN; }
#line 2467 "scanner.c"
yy225:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy305;
		default: goto yy30;
	}
yy226:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy306;
		default: goto yy227;
	}
yy227:
#line 269 "scanner.re"
	{ return TOKEN_SIXTH; }
#line 2485 "scanner.c"
yy228:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy307;
		default: goto yy30;
	}
yy229:
	++YYCURSOR;
#line 227 "scanner.re"
	{ return TOKEN_SIXTY; }
#line 2497 "scanner.c"
yy230:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy308;
		default: goto yy231;
	}
yy231:
#line 275 "scanner.re"
	{ return TOKEN_TENTH; }
#line 2508 "scanner.c"
yy232:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy309;
		default: goto yy233;
	}
yy233:
#line 266 "scanner.re"
	{ return TOKEN_THIRD; }
#line 2519 "scanner.c"
yy234:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy310;
		case 'I':
		case 'i': goto yy311;
		case 'Y':
		case 'y': goto yy312;
		default: goto yy30;
	}
yy235:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'A':
		case 'a': goto yy313;
		default: goto yy30;
	}
yy236:
	yyaccept = 19;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '-': goto yy153;
		default: goto yy237;
	}
yy237:
#line 203 "scanner.re"
	{ return TOKEN_THREE; }
#line 2553 "scanner.c"
yy238:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy314;
		default: goto yy30;
	}
yy239:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy315;
		default: goto yy30;
	}
yy240:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy316;
		default: goto yy30;
	}
yy241:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy317;
		case 'Y':
		case 'y': goto yy318;
		default: goto yy30;
	}
yy242:
	yych = *++YYCURSOR;
	switch (yych) {
		case ' ': goto yy67;
		case ',': goto yy244;
		case '.': goto yy245;
		default: goto yy30;
	}
yy243:
	yych = *++YYCURSOR;
	switch (yych) {
		case ',': goto yy252;
		case '.': goto yy68;
		default: goto yy30;
	}
yy244:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy319;
		default: goto yy30;
	}
yy245:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy321;
		default: goto yy30;
	}
yy246:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy323;
		default: goto yy30;
	}
yy247:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy325;
		default: goto yy30;
	}
yy248:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy326;
		default: goto yy30;
	}
yy249:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy327;
		default: goto yy30;
	}
yy250:
	yych = *++YYCURSOR;
	switch (yych) {
		case ',': goto yy179;
		case '.': goto yy328;
		default: goto yy30;
	}
yy251:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0xB7: goto yy329;
		default: goto yy30;
	}
yy252:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy330;
		default: goto yy30;
	}
yy253:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy332;
		default: goto yy30;
	}
yy254:
	yyaccept = 16;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '/': goto yy253;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy333;
		default: goto yy78;
	}
yy255:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy174;
		default: goto yy30;
	}
yy256:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy334;
		default: goto yy30;
	}
yy257:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy335;
		default: goto yy30;
	}
yy258:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'R':
		case 'r': goto yy336;
		default: goto yy30;
	}
yy259:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy337;
		default: goto yy30;
	}
yy260:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy338;
		default: goto yy30;
	}
yy261:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L':
		case 'l': goto yy339;
		default: goto yy30;
	}
yy262:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy340;
		default: goto yy30;
	}
yy263:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy342;
		default: goto yy30;
	}
yy264:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy343;
		default: goto yy265;
	}
yy265:
#line 271 "scanner.re"
	{ return TOKEN_EIGHTH; }
#line 2838 "scanner.c"
yy266:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy344;
		default: goto yy30;
	}
yy267:
	++YYCURSOR;
#line 229 "scanner.re"
	{ return TOKEN_EIGHTY; }
#line 2850 "scanner.c"
yy268:
	yyaccept = 20;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy345;
		default: goto yy269;
	}
yy269:
#line 211 "scanner.re"
	{ return TOKEN_ELEVEN; }
#line 2862 "scanner.c"
yy270:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy346;
		default: goto yy30;
	}
yy271:
	++YYCURSOR;
#line 335 "scanner.re"
	{ return TOKEN_FIFTHS; }
#line 2874 "scanner.c"
yy272:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy348;
		default: goto yy30;
	}
yy273:
	++YYCURSOR;
#line 310 "scanner.re"
	{ return TOKEN_FIRSTS; }
#line 2886 "scanner.c"
yy274:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy349;
		default: goto yy30;
	}
yy275:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy350;
		default: goto yy30;
	}
yy276:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy351;
		default: goto yy277;
	}
yy277:
#line 267 "scanner.re"
	{ return TOKEN_FOURTH; }
#line 2911 "scanner.c"
yy278:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy352;
		default: goto yy30;
	}
yy279:
	++YYCURSOR;
#line 225 "scanner.re"
	{ return TOKEN_FORTY; }
#line 2923 "scanner.c"
yy280:
	++YYCURSOR;
#line 369 "scanner.re"
	{ return TOKEN_HALVES; }
#line 2928 "scanner.c"
yy281:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'D':
		case 'd': goto yy353;
		default: goto yy30;
	}
yy282:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy355;
		default: goto yy30;
	}
yy283:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'V':
		case 'v': goto yy357;
		default: goto yy30;
	}
yy284:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy358;
		default: goto yy30;
	}
yy285:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy359;
		default: goto yy286;
	}
yy286:
#line 272 "scanner.re"
	{ return TOKEN_NINTH; }
#line 2967 "scanner.c"
yy287:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy360;
		default: goto yy30;
	}
yy288:
	++YYCURSOR;
#line 230 "scanner.re"
	{ return TOKEN_NINETY; }
#line 2979 "scanner.c"
yy289:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy361;
		default: goto yy30;
	}
yy290:
	++YYCURSOR;
#line 340 "scanner.re"
	{ return TOKEN_NINTHS; }
#line 2991 "scanner.c"
yy291:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'D':
		case 'd': goto yy362;
		default: goto yy30;
	}
yy292:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'G':
		case 'g': goto yy363;
		default: goto yy30;
	}
yy293:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'F':
		case 'f': goto yy364;
		default: goto yy30;
	}
yy294:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'U':
		case 'u': goto yy365;
		default: goto yy30;
	}
yy295:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L':
		case 'l': goto yy366;
		default: goto yy30;
	}
yy296:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy364;
		default: goto yy30;
	}
yy297:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'A':
		case 'a': goto yy367;
		default: goto yy30;
	}
yy298:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'V':
		case 'v': goto yy368;
		default: goto yy30;
	}
yy299:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'X':
		case 'x': goto yy364;
		default: goto yy30;
	}
yy300:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy369;
		default: goto yy30;
	}
yy301:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'R':
		case 'r': goto yy370;
		default: goto yy30;
	}
yy302:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy372;
		default: goto yy303;
	}
yy303:
#line 244 "scanner.re"
	{
            if (!state->parse_second) {
                // dont' parse "second" by default. easiest way to do this is to
                // treat it as a character token
                if (state->is_parsing) {
                    if (state->last_token != TOKEN_SEPARATOR) {
                        // number followed by character... e.g. "oneself"
                    } else {
                        // finish whatever we had and reset
                        Parse(pParser, 0, *yylval, state);
                    }

                    ParseReset(pParser);
                    state->is_parsing = false;
                }

                state->last_token = TOKEN_CHARACTERS;
                goto fast_path;
            } else {
                return TOKEN_SECOND;
            }
        }
#line 3100 "scanner.c"
yy304:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy373;
		case 'H':
		case 'h': goto yy374;
		case 'I':
		case 'i': goto yy376;
		case 'Y':
		case 'y': goto yy377;
		default: goto yy30;
	}
yy305:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy378;
		default: goto yy30;
	}
yy306:
	++YYCURSOR;
#line 336 "scanner.re"
	{ return TOKEN_SIXTHS; }
#line 3125 "scanner.c"
yy307:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy380;
		default: goto yy30;
	}
yy308:
	++YYCURSOR;
#line 342 "scanner.re"
	{ return TOKEN_TENTHS; }
#line 3137 "scanner.c"
yy309:
	++YYCURSOR;
#line 333 "scanner.re"
	{ return TOKEN_THIRDS; }
#line 3142 "scanner.c"
yy310:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy381;
		default: goto yy30;
	}
yy311:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy382;
		default: goto yy30;
	}
yy312:
	++YYCURSOR;
#line 223 "scanner.re"
	{ return TOKEN_THIRTY; }
#line 3161 "scanner.c"
yy313:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy383;
		default: goto yy30;
	}
yy314:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'O':
		case 'o': goto yy384;
		default: goto yy30;
	}
yy315:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy385;
		default: goto yy30;
	}
yy316:
	++YYCURSOR;
#line 212 "scanner.re"
	{ return TOKEN_TWELVE; }
#line 3187 "scanner.c"
yy317:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy387;
		default: goto yy30;
	}
yy318:
	++YYCURSOR;
#line 222 "scanner.re"
	{ return TOKEN_TWENTY; }
#line 3199 "scanner.c"
yy319:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy319;
		default: goto yy320;
	}
yy320:
#line 448 "scanner.re"
	{
            // create duplicate of string (to be modified inplace)
            size_t token_len = ss->cursor - ss->token;
            char* tmp = (char*)malloc(token_len + 1);
            strncpy(tmp, ss->token, token_len);
            tmp[token_len] = '\0';

            size_t len = remove_char_inplace(tmp, ss->cursor - ss->token, ' ');
            replace_char_inplace(tmp, len, ',', '.');

            // turn string version of number into double
            sds string_value = sdsnewlen(tmp, len);
            free(tmp);

            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_DECIMAL;
        }
#line 3236 "scanner.c"
yy321:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy321;
		default: goto yy322;
	}
yy322:
#line 430 "scanner.re"
	{
            // create duplicate of string (to be modified inplace)
            size_t token_len = ss->cursor - ss->token;
            char* tmp = (char*)malloc(token_len + 1);
            strncpy(tmp, ss->token, token_len);
            tmp[token_len] = '\0';

            size_t len = remove_char_inplace(tmp, ss->cursor - ss->token, ' ');

            // turn string version of number into double
            sds string_value = sdsnewlen(tmp, len);
            free(tmp);

            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_DECIMAL;
        }
#line 3272 "scanner.c"
yy323:
	yyaccept = 21;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '.': goto yy246;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy323;
		default: goto yy324;
	}
yy324:
#line 523 "scanner.re"
	{
            // create duplicate of string (to be modified inplace)
            size_t token_len = ss->cursor - ss->token;
            char* tmp = (char*)malloc(token_len + 1);
            strncpy(tmp, ss->token, token_len);
            tmp[token_len] = '\0';

            size_t len = remove_char_inplace(tmp, ss->cursor - ss->token, '\'');

            // turn string version of number into double
            sds string_value = sdsnewlen(tmp, len);
            free(tmp);

            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_DECIMAL;
        }
#line 3310 "scanner.c"
yy325:
	yych = *++YYCURSOR;
	switch (yych) {
		case ',': goto yy173;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy388;
		default: goto yy30;
	}
yy326:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy389;
		default: goto yy30;
	}
yy327:
	yyaccept = 14;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '.': goto yy249;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy327;
		default: goto yy175;
	}
yy328:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy390;
		default: goto yy30;
	}
yy329:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy392;
		default: goto yy30;
	}
yy330:
	yyaccept = 22;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case ',': goto yy252;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy330;
		default: goto yy331;
	}
yy331:
#line 486 "scanner.re"
	{
            // create duplicate of string (to be modified inplace)
            size_t token_len = ss->cursor - ss->token;
            char* tmp = (char*)malloc(token_len + 1);
            strncpy(tmp, ss->token, token_len);
            tmp[token_len] = '\0';

            size_t len = remove_char_inplace(tmp, ss->cursor - ss->token, '.');
            replace_char_inplace(tmp, len, ',', '.');

            // turn string version of number into double
            sds string_value = sdsnewlen(tmp, len);
            free(tmp);

            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_DECIMAL;
        }
#line 3427 "scanner.c"
yy332:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy394;
		default: goto yy30;
	}
yy333:
	yyaccept = 16;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '/': goto yy253;
		default: goto yy77;
	}
yy334:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy396;
		default: goto yy30;
	}
yy335:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'O':
		case 'o': goto yy397;
		default: goto yy30;
	}
yy336:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy398;
		default: goto yy30;
	}
yy337:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'O':
		case 'o': goto yy399;
		default: goto yy30;
	}
yy338:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'A':
		case 'a': goto yy400;
		default: goto yy30;
	}
yy339:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy401;
		default: goto yy30;
	}
yy340:
	yyaccept = 23;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy402;
		default: goto yy341;
	}
yy341:
#line 239 "scanner.re"
	{ return TOKEN_BILLION; }
#line 3511 "scanner.c"
yy342:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy403;
		default: goto yy30;
	}
yy343:
	++YYCURSOR;
#line 338 "scanner.re"
	{ return TOKEN_EIGHTHS; }
#line 3523 "scanner.c"
yy344:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy405;
		default: goto yy30;
	}
yy345:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy406;
		default: goto yy30;
	}
yy346:
	yyaccept = 24;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy408;
		default: goto yy347;
	}
yy347:
#line 215 "scanner.re"
	{ return TOKEN_FIFTEEN; }
#line 3549 "scanner.c"
yy348:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy409;
		default: goto yy30;
	}
yy349:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy411;
		default: goto yy30;
	}
yy350:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy412;
		default: goto yy30;
	}
yy351:
	++YYCURSOR;
#line 334 "scanner.re"
	{ return TOKEN_FOURTHS; }
#line 3575 "scanner.c"
yy352:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy414;
		default: goto yy30;
	}
yy353:
	yyaccept = 25;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy415;
		default: goto yy354;
	}
yy354:
#line 233 "scanner.re"
	{ return TOKEN_HUNDRED; }
#line 3594 "scanner.c"
yy355:
	yyaccept = 26;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy416;
		default: goto yy356;
	}
yy356:
#line 237 "scanner.re"
	{ return TOKEN_MILLION; }
#line 3606 "scanner.c"
yy357:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy417;
		default: goto yy30;
	}
yy358:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy418;
		default: goto yy30;
	}
yy359:
	++YYCURSOR;
#line 339 "scanner.re"
	{ return TOKEN_NINTHS; }
#line 3625 "scanner.c"
yy360:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy420;
		default: goto yy30;
	}
yy361:
	++YYCURSOR;
#line 220 "scanner.re"
	{ return TOKEN_NINETEEN; }
#line 3637 "scanner.c"
yy362:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '-': goto yy421;
		default: goto yy30;
	}
yy363:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy364;
		default: goto yy30;
	}
yy364:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy422;
		default: goto yy30;
	}
yy365:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'R':
		case 'r': goto yy364;
		default: goto yy30;
	}
yy366:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'F':
		case 'f': goto yy423;
		case 'V':
		case 'v': goto yy425;
		default: goto yy30;
	}
yy367:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'R':
		case 'r': goto yy426;
		default: goto yy30;
	}
yy368:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy296;
		default: goto yy30;
	}
yy369:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'R':
		case 'r': goto yy427;
		default: goto yy30;
	}
yy370:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy428;
		default: goto yy371;
	}
yy371:
#line 307 "scanner.re"
	{ return TOKEN_QUARTER; }
#line 3710 "scanner.c"
yy372:
	++YYCURSOR;
#line 311 "scanner.re"
	{
            if (!state->parse_second) {
                // dont' parse "second" by default. easiest way to do this is to
                // treat it as a character token
                if (state->is_parsing) {
                    if (state->last_token != TOKEN_SEPARATOR) {
                        // number followed by character... e.g. "oneself"
                    } else {
                        // finish whatever we had and reset
                        Parse(pParser, 0, *yylval, state);
                    }

                    ParseReset(pParser);
                    state->is_parsing = false;
                }

                state->last_token = TOKEN_CHARACTERS;
                goto fast_path;
            } else {
                return TOKEN_SECONDS;
            }
        }
#line 3736 "scanner.c"
yy373:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy429;
		default: goto yy30;
	}
yy374:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy430;
		default: goto yy375;
	}
yy375:
#line 270 "scanner.re"
	{ return TOKEN_SEVENTH; }
#line 3754 "scanner.c"
yy376:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy431;
		default: goto yy30;
	}
yy377:
	++YYCURSOR;
#line 228 "scanner.re"
	{ return TOKEN_SEVENTY; }
#line 3766 "scanner.c"
yy378:
	yyaccept = 27;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy432;
		default: goto yy379;
	}
yy379:
#line 216 "scanner.re"
	{ return TOKEN_SIXTEEN; }
#line 3778 "scanner.c"
yy380:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy433;
		default: goto yy30;
	}
yy381:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy435;
		default: goto yy30;
	}
yy382:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy437;
		default: goto yy30;
	}
yy383:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'D':
		case 'd': goto yy438;
		default: goto yy30;
	}
yy384:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy440;
		default: goto yy30;
	}
yy385:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy442;
		default: goto yy386;
	}
yy386:
#line 277 "scanner.re"
	{ return TOKEN_TWELFTH; }
#line 3824 "scanner.c"
yy387:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy443;
		default: goto yy30;
	}
yy388:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.': goto yy444;
		default: goto yy30;
	}
yy389:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy445;
		default: goto yy30;
	}
yy390:
	yyaccept = 28;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '.': goto yy328;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy390;
		default: goto yy391;
	}
yy391:
#line 541 "scanner.re"
	{
            // create duplicate of string (to be modified inplace)
            size_t token_len = ss->cursor - ss->token;
            char* tmp = (char*)malloc(token_len + 1);
            strncpy(tmp, ss->token, token_len);
            tmp[token_len] = '\0';

            size_t len = remove_char_inplace(tmp, ss->cursor - ss->token, ',');

            // turn string version of number into double
            sds string_value = sdsnewlen(tmp, len);
            free(tmp);

            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_DECIMAL;
        }
#line 3890 "scanner.c"
yy392:
	yyaccept = 29;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy392;
		case 0xC2: goto yy251;
		default: goto yy393;
	}
yy393:
#line 467 "scanner.re"
	{
            // create duplicate of string (to be modified inplace)
            size_t token_len = ss->cursor - ss->token;
            char* tmp = (char*)malloc(token_len + 1);
            strncpy(tmp, ss->token, token_len);
            tmp[token_len] = '\0';

            size_t len = remove_char_inplace(tmp, ss->cursor - ss->token, ',');
            len = replace_two_byte_char_inplace((unsigned char*)tmp, len, (unsigned char*)"·", '.');

            // turn string version of number into double
            sds string_value = sdsnewlen(tmp, len);
            free(tmp);

            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_DECIMAL;
        }
#line 3929 "scanner.c"
yy394:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy446;
		default: goto yy395;
	}
yy395:
#line 380 "scanner.re"
	{
            if (state->is_parsing) {
                if (state->last_token != TOKEN_SEPARATOR) {
                    // number followed by character... e.g. "oneself"
                } else {
                    // finish whatever we had and reset
                    Parse(pParser, 0, *yylval, state);
                }

                ParseReset(pParser);
                state->is_parsing = false;
            }

            state->last_token = TOKEN_CHARACTERS;
            goto fast_path;
        }
#line 3963 "scanner.c"
yy396:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy250;
		default: goto yy30;
	}
yy397:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy447;
		default: goto yy30;
	}
yy398:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'D':
		case 'd': goto yy449;
		default: goto yy30;
	}
yy399:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy451;
		default: goto yy30;
	}
yy400:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy453;
		default: goto yy30;
	}
yy401:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'O':
		case 'o': goto yy454;
		default: goto yy30;
	}
yy402:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy455;
		default: goto yy30;
	}
yy403:
	yyaccept = 30;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy457;
		default: goto yy404;
	}
yy404:
#line 218 "scanner.re"
	{ return TOKEN_EIGHTEEN; }
#line 4032 "scanner.c"
yy405:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy458;
		default: goto yy30;
	}
yy406:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy460;
		default: goto yy407;
	}
yy407:
#line 276 "scanner.re"
	{ return TOKEN_ELEVENTH; }
#line 4050 "scanner.c"
yy408:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy461;
		default: goto yy30;
	}
yy409:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy463;
		default: goto yy410;
	}
yy410:
#line 290 "scanner.re"
	{ return TOKEN_FIFTIETH; }
#line 4068 "scanner.c"
yy411:
	++YYCURSOR;
#line 288 "scanner.re"
	{ return TOKEN_FOURTIETH; }
#line 4073 "scanner.c"
yy412:
	yyaccept = 31;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy464;
		default: goto yy413;
	}
yy413:
#line 214 "scanner.re"
	{ return TOKEN_FOURTEEN; }
#line 4085 "scanner.c"
yy414:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy465;
		default: goto yy30;
	}
yy415:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy467;
		default: goto yy30;
	}
yy416:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy469;
		default: goto yy30;
	}
yy417:
	++YYCURSOR;
#line 198 "scanner.re"
	{ return TOKEN_NEGATIVE; }
#line 4111 "scanner.c"
yy418:
	yyaccept = 32;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy471;
		default: goto yy419;
	}
yy419:
#line 219 "scanner.re"
	{ return TOKEN_NINETEEN; }
#line 4123 "scanner.c"
yy420:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy472;
		default: goto yy30;
	}
yy421:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '-': goto yy421;
		case 'E':
		case 'e': goto yy474;
		case 'F':
		case 'f': goto yy475;
		case 'N':
		case 'n': goto yy476;
		case 'O':
		case 'o': goto yy477;
		case 'S':
		case 's': goto yy478;
		case 'T':
		case 't': goto yy479;
		default: goto yy30;
	}
yy422:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy480;
		default: goto yy30;
	}
yy423:
	++YYCURSOR;
yy424:
#line 171 "scanner.re"
	{
            const char* s = ss->token; const char* e = ss->cursor;
            const char* ws = s; while (ws<e && (*ws!=' '&&*ws!='\t'&&*ws!='\r'&&*ws!='\n'&&*ws!='\f'&&*ws!='-')) ws++;
            double num=0; (void)map_card_small(s, (size_t)(ws - s), &num);
            while (ws<e && (*ws==' '||*ws=='\t'||*ws=='\r'||*ws=='\n'||*ws=='\f'||*ws=='-')) ws++;
            double den=0; (void)map_denom_word(ws, (size_t)(e - ws), &den);
            #ifdef SCANNER_FRACTIONS
            (*yylval).is_frac = true; (*yylval).frac_num = num; (*yylval).frac_denom = den; return TOKEN_FRACTION;
            #else
            if (state->is_parsing) {
                if (state->last_token != TOKEN_SEPARATOR) {
                } else {
                    Parse(pParser, 0, *yylval, state);
                }
                ParseReset(pParser);
                state->is_parsing = false;
            }
            state->last_token = TOKEN_CHARACTERS;
            goto fast_path;
            #endif
        }
#line 4186 "scanner.c"
yy425:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy481;
		default: goto yy30;
	}
yy426:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy482;
		default: goto yy30;
	}
yy427:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'D':
		case 'd': goto yy480;
		default: goto yy30;
	}
yy428:
	++YYCURSOR;
#line 368 "scanner.re"
	{ return TOKEN_QUARTERS; }
#line 4212 "scanner.c"
yy429:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy483;
		default: goto yy30;
	}
yy430:
	++YYCURSOR;
#line 337 "scanner.re"
	{ return TOKEN_SEVENTHS; }
#line 4224 "scanner.c"
yy431:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy485;
		default: goto yy30;
	}
yy432:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy486;
		default: goto yy30;
	}
yy433:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy488;
		default: goto yy434;
	}
yy434:
#line 291 "scanner.re"
	{ return TOKEN_SIXTIETH; }
#line 4249 "scanner.c"
yy435:
	yyaccept = 33;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy489;
		default: goto yy436;
	}
yy436:
#line 213 "scanner.re"
	{ return TOKEN_THIRTEEN; }
#line 4261 "scanner.c"
yy437:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy490;
		default: goto yy30;
	}
yy438:
	yyaccept = 34;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy492;
		default: goto yy439;
	}
yy439:
#line 235 "scanner.re"
	{ return TOKEN_THOUSAND; }
#line 4280 "scanner.c"
yy440:
	yyaccept = 35;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy493;
		default: goto yy441;
	}
yy441:
#line 241 "scanner.re"
	{ return TOKEN_TRILLION; }
#line 4292 "scanner.c"
yy442:
	++YYCURSOR;
#line 344 "scanner.re"
	{ return TOKEN_TWELFTHS; }
#line 4297 "scanner.c"
yy443:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy494;
		default: goto yy30;
	}
yy444:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy496;
		default: goto yy30;
	}
yy445:
	yyaccept = 14;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case ',': goto yy248;
		case '.': goto yy249;
		case 0xC2: goto yy251;
		default: goto yy175;
	}
yy446:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy498;
		default: goto yy395;
	}
yy447:
	yyaccept = 36;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy499;
		default: goto yy448;
	}
yy448:
#line 238 "scanner.re"
	{ return TOKEN_BILLION; }
#line 4355 "scanner.c"
yy449:
	yyaccept = 37;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy500;
		default: goto yy450;
	}
yy450:
#line 232 "scanner.re"
	{ return TOKEN_HUNDRED; }
#line 4367 "scanner.c"
yy451:
	yyaccept = 38;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy501;
		default: goto yy452;
	}
yy452:
#line 236 "scanner.re"
	{ return TOKEN_MILLION; }
#line 4379 "scanner.c"
yy453:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'D':
		case 'd': goto yy502;
		default: goto yy30;
	}
yy454:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy504;
		default: goto yy30;
	}
yy455:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy506;
		default: goto yy456;
	}
yy456:
#line 303 "scanner.re"
	{ return TOKEN_BILLIONTH; }
#line 4404 "scanner.c"
yy457:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy507;
		default: goto yy30;
	}
yy458:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy509;
		default: goto yy459;
	}
yy459:
#line 293 "scanner.re"
	{ return TOKEN_EIGHTIETH; }
#line 4422 "scanner.c"
yy460:
	++YYCURSOR;
#line 343 "scanner.re"
	{ return TOKEN_ELEVENTHS; }
#line 4427 "scanner.c"
yy461:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy510;
		default: goto yy462;
	}
yy462:
#line 280 "scanner.re"
	{ return TOKEN_FIFTEENTH; }
#line 4438 "scanner.c"
yy463:
	++YYCURSOR;
#line 356 "scanner.re"
	{ return TOKEN_FIFTIETHS; }
#line 4443 "scanner.c"
yy464:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy511;
		default: goto yy30;
	}
yy465:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy513;
		default: goto yy466;
	}
yy466:
#line 289 "scanner.re"
	{ return TOKEN_FOURTIETH; }
#line 4461 "scanner.c"
yy467:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy514;
		default: goto yy468;
	}
yy468:
#line 297 "scanner.re"
	{ return TOKEN_HUNDREDTH; }
#line 4472 "scanner.c"
yy469:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy515;
		default: goto yy470;
	}
yy470:
#line 301 "scanner.re"
	{ return TOKEN_MILLIONTH; }
#line 4483 "scanner.c"
yy471:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy516;
		default: goto yy30;
	}
yy472:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy518;
		default: goto yy473;
	}
yy473:
#line 294 "scanner.re"
	{ return TOKEN_NINETIETH; }
#line 4501 "scanner.c"
yy474:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy519;
		default: goto yy30;
	}
yy475:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy520;
		case 'O':
		case 'o': goto yy521;
		default: goto yy30;
	}
yy476:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy477;
		default: goto yy30;
	}
yy477:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy522;
		default: goto yy30;
	}
yy478:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy523;
		case 'I':
		case 'i': goto yy524;
		default: goto yy30;
	}
yy479:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy525;
		case 'W':
		case 'w': goto yy526;
		default: goto yy30;
	}
yy480:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy423;
		default: goto yy424;
	}
yy481:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy423;
		default: goto yy30;
	}
yy482:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy527;
		default: goto yy30;
	}
yy483:
	yyaccept = 39;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy528;
		default: goto yy484;
	}
yy484:
#line 217 "scanner.re"
	{ return TOKEN_SEVENTEEN; }
#line 4582 "scanner.c"
yy485:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy529;
		default: goto yy30;
	}
yy486:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy531;
		default: goto yy487;
	}
yy487:
#line 281 "scanner.re"
	{ return TOKEN_SIXTEENTH; }
#line 4600 "scanner.c"
yy488:
	++YYCURSOR;
#line 357 "scanner.re"
	{ return TOKEN_SIXTIETHS; }
#line 4605 "scanner.c"
yy489:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy532;
		default: goto yy30;
	}
yy490:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy534;
		default: goto yy491;
	}
yy491:
#line 287 "scanner.re"
	{ return TOKEN_THIRTIETH; }
#line 4623 "scanner.c"
yy492:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy535;
		default: goto yy30;
	}
yy493:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy537;
		default: goto yy30;
	}
yy494:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy539;
		default: goto yy495;
	}
yy495:
#line 286 "scanner.re"
	{ return TOKEN_TWENTIETH; }
#line 4648 "scanner.c"
yy496:
	yyaccept = 40;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '.': goto yy444;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy496;
		default: goto yy497;
	}
yy497:
#line 505 "scanner.re"
	{
            // create duplicate of string (to be modified inplace)
            size_t token_len = ss->cursor - ss->token;
            char* tmp = (char*)malloc(token_len + 1);
            strncpy(tmp, ss->token, token_len);
            tmp[token_len] = '\0';

            size_t len = remove_char_inplace(tmp, ss->cursor - ss->token, ',');

            // turn string version of number into double
            sds string_value = sdsnewlen(tmp, len);
            free(tmp);

            sscanf(string_value, "%lf", &(*yylval).dbl);
            sdsfree(string_value);

            return TOKEN_DECIMAL;
        }
#line 4686 "scanner.c"
yy498:
	++YYCURSOR;
	goto yy395;
yy499:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy540;
		default: goto yy30;
	}
yy500:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy541;
		default: goto yy30;
	}
yy501:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy542;
		default: goto yy30;
	}
yy502:
	yyaccept = 41;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy543;
		default: goto yy503;
	}
yy503:
#line 234 "scanner.re"
	{ return TOKEN_THOUSAND; }
#line 4722 "scanner.c"
yy504:
	yyaccept = 42;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'T':
		case 't': goto yy544;
		default: goto yy505;
	}
yy505:
#line 240 "scanner.re"
	{ return TOKEN_TRILLION; }
#line 4734 "scanner.c"
yy506:
	++YYCURSOR;
#line 365 "scanner.re"
	{ return TOKEN_BILLIONTHS; }
#line 4739 "scanner.c"
yy507:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy545;
		default: goto yy508;
	}
yy508:
#line 283 "scanner.re"
	{ return TOKEN_EIGHTEENTH; }
#line 4750 "scanner.c"
yy509:
	++YYCURSOR;
#line 359 "scanner.re"
	{ return TOKEN_EIGHTIETHS; }
#line 4755 "scanner.c"
yy510:
	++YYCURSOR;
#line 347 "scanner.re"
	{ return TOKEN_FIFTEENTHS; }
#line 4760 "scanner.c"
yy511:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy546;
		default: goto yy512;
	}
yy512:
#line 279 "scanner.re"
	{ return TOKEN_FOURTEENTH; }
#line 4771 "scanner.c"
yy513:
	++YYCURSOR;
#line 355 "scanner.re"
	{ return TOKEN_FOURTIETHS; }
#line 4776 "scanner.c"
yy514:
	++YYCURSOR;
#line 362 "scanner.re"
	{ return TOKEN_HUNDREDTHS; }
#line 4781 "scanner.c"
yy515:
	++YYCURSOR;
#line 364 "scanner.re"
	{ return TOKEN_MILLIONTHS; }
#line 4786 "scanner.c"
yy516:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy547;
		default: goto yy517;
	}
yy517:
#line 284 "scanner.re"
	{ return TOKEN_NINETEENTH; }
#line 4797 "scanner.c"
yy518:
	++YYCURSOR;
#line 360 "scanner.re"
	{ return TOKEN_NINETIETHS; }
#line 4802 "scanner.c"
yy519:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'G':
		case 'g': goto yy548;
		default: goto yy30;
	}
yy520:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'V':
		case 'v': goto yy522;
		default: goto yy30;
	}
yy521:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'U':
		case 'u': goto yy549;
		default: goto yy30;
	}
yy522:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy550;
		default: goto yy30;
	}
yy523:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'V':
		case 'v': goto yy551;
		default: goto yy30;
	}
yy524:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'X':
		case 'x': goto yy550;
		default: goto yy30;
	}
yy525:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'R':
		case 'r': goto yy552;
		default: goto yy30;
	}
yy526:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'O':
		case 'o': goto yy550;
		default: goto yy30;
	}
yy527:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'R':
		case 'r': goto yy480;
		default: goto yy30;
	}
yy528:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy553;
		default: goto yy30;
	}
yy529:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy555;
		default: goto yy530;
	}
yy530:
#line 292 "scanner.re"
	{ return TOKEN_SEVENTIETH; }
#line 4883 "scanner.c"
yy531:
	++YYCURSOR;
#line 348 "scanner.re"
	{ return TOKEN_SIXTEENTHS; }
#line 4888 "scanner.c"
yy532:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy556;
		default: goto yy533;
	}
yy533:
#line 278 "scanner.re"
	{ return TOKEN_THIRTEENTH; }
#line 4899 "scanner.c"
yy534:
	++YYCURSOR;
#line 354 "scanner.re"
	{ return TOKEN_THIRTIETHS; }
#line 4904 "scanner.c"
yy535:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy557;
		default: goto yy536;
	}
yy536:
#line 299 "scanner.re"
	{ return TOKEN_THOUSANDTH; }
#line 4915 "scanner.c"
yy537:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy558;
		default: goto yy538;
	}
yy538:
#line 305 "scanner.re"
	{ return TOKEN_TRILLIONTH; }
#line 4926 "scanner.c"
yy539:
	++YYCURSOR;
#line 353 "scanner.re"
	{ return TOKEN_TWENTIETHS; }
#line 4931 "scanner.c"
yy540:
	++YYCURSOR;
#line 302 "scanner.re"
	{ return TOKEN_BILLIONTH; }
#line 4936 "scanner.c"
yy541:
	++YYCURSOR;
#line 296 "scanner.re"
	{ return TOKEN_HUNDREDTH; }
#line 4941 "scanner.c"
yy542:
	++YYCURSOR;
#line 300 "scanner.re"
	{ return TOKEN_MILLIONTH; }
#line 4946 "scanner.c"
yy543:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy559;
		default: goto yy30;
	}
yy544:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy560;
		default: goto yy30;
	}
yy545:
	++YYCURSOR;
#line 350 "scanner.re"
	{ return TOKEN_EIGHTEENTHS; }
#line 4965 "scanner.c"
yy546:
	++YYCURSOR;
#line 346 "scanner.re"
	{ return TOKEN_FOURTEENTHS; }
#line 4970 "scanner.c"
yy547:
	++YYCURSOR;
#line 351 "scanner.re"
	{ return TOKEN_NINETEENTHS; }
#line 4975 "scanner.c"
yy548:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy561;
		default: goto yy30;
	}
yy549:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'R':
		case 'r': goto yy550;
		default: goto yy30;
	}
yy550:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '-': goto yy562;
		default: goto yy30;
	}
yy551:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy563;
		default: goto yy30;
	}
yy552:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy522;
		default: goto yy30;
	}
yy553:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy564;
		default: goto yy554;
	}
yy554:
#line 282 "scanner.re"
	{ return TOKEN_SEVENTEENTH; }
#line 5025 "scanner.c"
yy555:
	++YYCURSOR;
#line 358 "scanner.re"
	{ return TOKEN_SEVENTIETHS; }
#line 5030 "scanner.c"
yy556:
	++YYCURSOR;
#line 345 "scanner.re"
	{ return TOKEN_THIRTEENTHS; }
#line 5035 "scanner.c"
yy557:
	++YYCURSOR;
#line 363 "scanner.re"
	{ return TOKEN_THOUSANDTHS; }
#line 5040 "scanner.c"
yy558:
	++YYCURSOR;
#line 366 "scanner.re"
	{ return TOKEN_TRILLIONTHS; }
#line 5045 "scanner.c"
yy559:
	++YYCURSOR;
#line 298 "scanner.re"
	{ return TOKEN_THOUSANDTH; }
#line 5050 "scanner.c"
yy560:
	++YYCURSOR;
#line 304 "scanner.re"
	{ return TOKEN_TRILLIONTH; }
#line 5055 "scanner.c"
yy561:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy550;
		default: goto yy30;
	}
yy562:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '-': goto yy562;
		case 'E':
		case 'e': goto yy565;
		case 'F':
		case 'f': goto yy566;
		case 'H':
		case 'h': goto yy567;
		case 'N':
		case 'n': goto yy568;
		case 'Q':
		case 'q': goto yy569;
		case 'S':
		case 's': goto yy570;
		case 'T':
		case 't': goto yy571;
		default: goto yy30;
	}
yy563:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy550;
		default: goto yy30;
	}
yy564:
	++YYCURSOR;
#line 349 "scanner.re"
	{ return TOKEN_SEVENTEENTHS; }
#line 5099 "scanner.c"
yy565:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy572;
		default: goto yy30;
	}
yy566:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy573;
		case 'O':
		case 'o': goto yy574;
		default: goto yy30;
	}
yy567:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'A':
		case 'a': goto yy575;
		default: goto yy30;
	}
yy568:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy576;
		default: goto yy30;
	}
yy569:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'U':
		case 'u': goto yy577;
		default: goto yy30;
	}
yy570:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy578;
		case 'I':
		case 'i': goto yy579;
		default: goto yy30;
	}
yy571:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy580;
		default: goto yy30;
	}
yy572:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'G':
		case 'g': goto yy581;
		default: goto yy30;
	}
yy573:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'F':
		case 'f': goto yy582;
		default: goto yy30;
	}
yy574:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'U':
		case 'u': goto yy583;
		default: goto yy30;
	}
yy575:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L':
		case 'l': goto yy584;
		default: goto yy30;
	}
yy576:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N':
		case 'n': goto yy582;
		default: goto yy30;
	}
yy577:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'A':
		case 'a': goto yy585;
		default: goto yy30;
	}
yy578:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'V':
		case 'v': goto yy586;
		default: goto yy30;
	}
yy579:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'X':
		case 'x': goto yy582;
		default: goto yy30;
	}
yy580:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I':
		case 'i': goto yy587;
		default: goto yy30;
	}
yy581:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy582;
		default: goto yy30;
	}
yy582:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy588;
		default: goto yy30;
	}
yy583:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'R':
		case 'r': goto yy582;
		default: goto yy30;
	}
yy584:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'F':
		case 'f': goto yy589;
		case 'V':
		case 'v': goto yy591;
		default: goto yy30;
	}
yy585:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'R':
		case 'r': goto yy592;
		default: goto yy30;
	}
yy586:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy576;
		default: goto yy30;
	}
yy587:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'R':
		case 'r': goto yy593;
		default: goto yy30;
	}
yy588:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'H':
		case 'h': goto yy594;
		default: goto yy30;
	}
yy589:
	++YYCURSOR;
yy590:
#line 140 "scanner.re"
	{
            const char* s = ss->token; const char* e = ss->cursor;
            // find 'and'
            const char* andp = strstr(s, "and");
            if (andp) {
                // left card
                const char* ws1 = s; while (ws1<andp && (*ws1!=' '&&*ws1!='\t'&&*ws1!='\r'&&*ws1!='\n'&&*ws1!='\f'&&*ws1!='-')) ws1++;
                double x=0; (void)map_card_small(s, (size_t)(ws1 - s), &x);
                const char* p = andp + 3; while (p<e && (*p==' '||*p=='\t'||*p=='\r'||*p=='\n'||*p=='\f'||*p=='-')) p++;
                const char* ws2 = p; while (ws2<e && (*ws2!=' '&&*ws2!='\t'&&*ws2!='\r'&&*ws2!='\n'&&*ws2!='\f'&&*ws2!='-')) ws2++;
                double y=0; (void)map_card_small(p, (size_t)(ws2 - p), &y);
                while (ws2<e && (*ws2==' '||*ws2=='\t'||*ws2=='\r'||*ws2=='\n'||*ws2=='\f'||*ws2=='-')) ws2++;
                double den=0; (void)map_denom_word(ws2, (size_t)(e - ws2), &den);
                #ifdef SCANNER_FRACTIONS
                (*yylval).is_frac = true; (*yylval).frac_num = x*den + y; (*yylval).frac_denom = den; return TOKEN_FRACTION;
                #else
                if (state->is_parsing) {
                    if (state->last_token != TOKEN_SEPARATOR) {
                    } else {
                        Parse(pParser, 0, *yylval, state);
                    }
                    ParseReset(pParser);
                    state->is_parsing = false;
                }
                state->last_token = TOKEN_CHARACTERS;
                goto fast_path;
                #endif
            }
        }
#line 5307 "scanner.c"
yy591:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy595;
		default: goto yy30;
	}
yy592:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'T':
		case 't': goto yy596;
		default: goto yy30;
	}
yy593:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'D':
		case 'd': goto yy594;
		default: goto yy30;
	}
yy594:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy589;
		default: goto yy590;
	}
yy595:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S':
		case 's': goto yy589;
		default: goto yy30;
	}
yy596:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E':
		case 'e': goto yy597;
		default: goto yy30;
	}
yy597:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'R':
		case 'r': goto yy594;
		default: goto yy30;
	}
}
#line 621 "scanner.re"

}
