/* Generated by re2c 0.16 on Sun Dec  4 14:07:30 2016 */
#line 1 "scanner.re"
/* OmNomNum 0.0.1 -- Gobbles up numbers in strings.
 *
 * Copyright (c) 2016, Jesse Buesking <jessebuesking at gmail dot com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *   * Redistributions of source code must retain the above copyright notice,
 *     this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *   * Neither the name of OmNomNum nor the names of its contributors may be used
 *     to endorse or promote products derived from this software without
 *     specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include "scanner.h"

#define TOKEN_SEPARATOR 10000

ScannerValue omnomnum_scanner_start(ParserState *state, scanstate *ss) {
    ScannerValue value;
    ss->token = ss->cursor;
//std:
    
#line 43 "scanner.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if ((YYLIMIT - YYCURSOR) < 14) YYFILL(14);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\n':
	case '\f':
	case '\r':
	case ' ':
	case '-':	goto yy6;
	case '.':	goto yy9;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy10;
	case 'A':
	case 'a':	goto yy12;
	case 'B':
	case 'b':	goto yy13;
	case 'E':
	case 'e':	goto yy14;
	case 'F':
	case 'f':	goto yy15;
	case 'H':
	case 'h':	goto yy16;
	case 'M':
	case 'm':	goto yy17;
	case 'N':
	case 'n':	goto yy18;
	case 'O':
	case 'o':	goto yy19;
	case 'Q':
	case 'q':	goto yy20;
	case 'S':
	case 's':	goto yy21;
	case 'T':
	case 't':	goto yy22;
	case 'Z':
	case 'z':	goto yy23;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
#line 194 "scanner.re"
	{ value.token = 0; return value; }
#line 98 "scanner.c"
yy4:
	++YYCURSOR;
yy5:
#line 196 "scanner.re"
	{ value.token = TOKEN_CHARACTERS; return value; }
#line 104 "scanner.c"
yy6:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\f':
	case '\r':
	case ' ':
	case '-':	goto yy6;
	default:	goto yy8;
	}
yy8:
#line 192 "scanner.re"
	{ value.token = TOKEN_SEPARATOR; return value; }
#line 121 "scanner.c"
yy9:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy24;
	default:	goto yy5;
	}
yy10:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':	goto yy26;
	case '/':	goto yy28;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy29;
	default:	goto yy11;
	}
yy11:
#line 52 "scanner.re"
	{ value.token = TOKEN_NUMBER; return value; }
#line 158 "scanner.c"
yy12:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ' ':	goto yy30;
	case 'N':
	case 'n':	goto yy31;
	default:	goto yy5;
	}
yy13:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':
	case 'i':	goto yy32;
	default:	goto yy5;
	}
yy14:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':
	case 'i':	goto yy33;
	case 'L':
	case 'l':	goto yy34;
	default:	goto yy5;
	}
yy15:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':
	case 'i':	goto yy35;
	case 'O':
	case 'o':	goto yy36;
	default:	goto yy5;
	}
yy16:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'A':
	case 'a':	goto yy37;
	case 'U':
	case 'u':	goto yy38;
	default:	goto yy5;
	}
yy17:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':
	case 'i':	goto yy39;
	default:	goto yy5;
	}
yy18:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy40;
	case 'I':
	case 'i':	goto yy41;
	default:	goto yy5;
	}
yy19:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'N':
	case 'n':	goto yy42;
	default:	goto yy5;
	}
yy20:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'U':
	case 'u':	goto yy43;
	default:	goto yy5;
	}
yy21:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy44;
	case 'I':
	case 'i':	goto yy45;
	default:	goto yy5;
	}
yy22:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy46;
	case 'H':
	case 'h':	goto yy47;
	case 'R':
	case 'r':	goto yy48;
	case 'W':
	case 'w':	goto yy49;
	default:	goto yy5;
	}
yy23:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy50;
	default:	goto yy5;
	}
yy24:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy24;
	default:	goto yy11;
	}
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy24;
	default:	goto yy27;
	}
yy27:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy11;
	case 1: 	goto yy5;
	case 2: 	goto yy61;
	case 3: 	goto yy81;
	case 4: 	goto yy83;
	case 5: 	goto yy109;
	case 6: 	goto yy116;
	case 7: 	goto yy53;
	case 8: 	goto yy143;
	case 9: 	goto yy166;
	case 10: 	goto yy200;
	case 11: 	goto yy245;
	case 12: 	goto yy250;
	case 13: 	goto yy255;
	case 14: 	goto yy257;
	case 15: 	goto yy272;
	case 16: 	goto yy290;
	case 17: 	goto yy298;
	case 18: 	goto yy305;
	case 19: 	goto yy313;
	case 20: 	goto yy316;
	case 21: 	goto yy318;
	default:	goto yy347;
	}
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy51;
	default:	goto yy27;
	}
yy29:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':	goto yy26;
	case '/':	goto yy54;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy55;
	default:	goto yy11;
	}
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'B':
	case 'b':	goto yy56;
	case 'H':
	case 'h':	goto yy57;
	case 'M':
	case 'm':	goto yy58;
	case 'T':
	case 't':	goto yy59;
	default:	goto yy27;
	}
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy60;
	default:	goto yy27;
	}
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy62;
	default:	goto yy27;
	}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy63;
	default:	goto yy27;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy64;
	default:	goto yy27;
	}
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy65;
	case 'R':
	case 'r':	goto yy66;
	case 'V':
	case 'v':	goto yy67;
	default:	goto yy27;
	}
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy68;
	case 'U':
	case 'u':	goto yy69;
	default:	goto yy27;
	}
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy70;
	default:	goto yy27;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy71;
	default:	goto yy27;
	}
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy72;
	default:	goto yy27;
	}
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy73;
	default:	goto yy27;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy74;
	default:	goto yy27;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy75;
	default:	goto yy27;
	}
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy77;
	default:	goto yy27;
	}
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy78;
	case 'V':
	case 'v':	goto yy79;
	default:	goto yy27;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'X':
	case 'x':	goto yy80;
	default:	goto yy27;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy82;
	default:	goto yy27;
	}
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy84;
	case 'O':
	case 'o':	goto yy85;
	case 'R':
	case 'r':	goto yy86;
	default:	goto yy27;
	}
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy87;
	default:	goto yy27;
	}
yy49:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy88;
	case 'O':
	case 'o':	goto yy89;
	default:	goto yy27;
	}
yy50:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy91;
	default:	goto yy27;
	}
yy51:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy52:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy51;
	default:	goto yy53;
	}
yy53:
#line 51 "scanner.re"
	{ value.token = TOKEN_CHARACTERS; return value; }
#line 552 "scanner.c"
yy54:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy92;
	default:	goto yy27;
	}
yy55:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':	goto yy26;
	case '/':	goto yy54;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy93;
	default:	goto yy11;
	}
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy94;
	default:	goto yy27;
	}
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy95;
	default:	goto yy27;
	}
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy96;
	default:	goto yy27;
	}
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy97;
	case 'R':
	case 'r':	goto yy98;
	default:	goto yy27;
	}
yy60:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ' ':	goto yy99;
	default:	goto yy61;
	}
yy61:
#line 54 "scanner.re"
	{ value.token = TOKEN_AND; return value; }
#line 626 "scanner.c"
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy100;
	default:	goto yy27;
	}
yy63:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy101;
	default:	goto yy27;
	}
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'V':
	case 'v':	goto yy102;
	default:	goto yy27;
	}
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy103;
	default:	goto yy27;
	}
yy66:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy104;
	default:	goto yy27;
	}
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy105;
	default:	goto yy27;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy107;
	default:	goto yy27;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy108;
	default:	goto yy27;
	}
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy110;
	default:	goto yy27;
	}
yy71:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy112;
	default:	goto yy27;
	}
yy72:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy113;
	default:	goto yy27;
	}
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy114;
	default:	goto yy27;
	}
yy74:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy115;
	case 'T':
	case 't':	goto yy117;
	default:	goto yy27;
	}
yy75:
	++YYCURSOR;
#line 60 "scanner.re"
	{ value.token = TOKEN_ONE; return value; }
#line 724 "scanner.c"
yy77:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy118;
	default:	goto yy27;
	}
yy78:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy119;
	default:	goto yy27;
	}
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy120;
	default:	goto yy27;
	}
yy80:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy121;
	default:	goto yy81;
	}
yy81:
#line 65 "scanner.re"
	{ value.token = TOKEN_SIX; return value; }
#line 757 "scanner.c"
yy82:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy122;
	default:	goto yy83;
	}
yy83:
#line 69 "scanner.re"
	{ value.token = TOKEN_TEN; return value; }
#line 769 "scanner.c"
yy84:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy123;
	default:	goto yy27;
	}
yy85:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy124;
	default:	goto yy27;
	}
yy86:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy125;
	default:	goto yy27;
	}
yy87:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy126;
	default:	goto yy27;
	}
yy88:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy127;
	case 'N':
	case 'n':	goto yy128;
	default:	goto yy27;
	}
yy89:
	++YYCURSOR;
#line 61 "scanner.re"
	{ value.token = TOKEN_TWO; return value; }
#line 811 "scanner.c"
yy91:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy129;
	default:	goto yy27;
	}
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy131;
	default:	goto yy53;
	}
yy93:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '/':	goto yy54;
	default:	goto yy133;
	}
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy134;
	default:	goto yy27;
	}
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy135;
	default:	goto yy27;
	}
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy136;
	default:	goto yy27;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy137;
	default:	goto yy27;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy138;
	default:	goto yy27;
	}
yy99:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy139;
	default:	goto yy27;
	}
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy141;
	default:	goto yy27;
	}
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy142;
	default:	goto yy27;
	}
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy144;
	default:	goto yy27;
	}
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy145;
	case 'H':
	case 'h':	goto yy146;
	case 'I':
	case 'i':	goto yy148;
	case 'Y':
	case 'y':	goto yy149;
	default:	goto yy27;
	}
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy151;
	default:	goto yy27;
	}
yy105:
	++YYCURSOR;
#line 64 "scanner.re"
	{ value.token = TOKEN_FIVE; return value; }
#line 928 "scanner.c"
yy107:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'Y':
	case 'y':	goto yy153;
	default:	goto yy27;
	}
yy108:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy155;
	default:	goto yy109;
	}
yy109:
#line 63 "scanner.re"
	{ value.token = TOKEN_FOUR; return value; }
#line 947 "scanner.c"
yy110:
	++YYCURSOR;
#line 149 "scanner.re"
	{ value.token = TOKEN_HALF; return value; }
#line 952 "scanner.c"
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy156;
	default:	goto yy27;
	}
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy157;
	default:	goto yy27;
	}
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy158;
	default:	goto yy27;
	}
yy115:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy159;
	default:	goto yy116;
	}
yy116:
#line 68 "scanner.re"
	{ value.token = TOKEN_NINE; return value; }
#line 985 "scanner.c"
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy160;
	case 'H':
	case 'h':	goto yy161;
	default:	goto yy27;
	}
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy163;
	default:	goto yy27;
	}
yy119:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy164;
	default:	goto yy27;
	}
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy165;
	default:	goto yy27;
	}
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy167;
	case 'H':
	case 'h':	goto yy168;
	case 'I':
	case 'i':	goto yy170;
	case 'Y':
	case 'y':	goto yy171;
	default:	goto yy27;
	}
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy173;
	default:	goto yy27;
	}
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy175;
	case 'T':
	case 't':	goto yy177;
	default:	goto yy27;
	}
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy178;
	default:	goto yy27;
	}
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy179;
	default:	goto yy27;
	}
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy181;
	default:	goto yy27;
	}
yy127:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy182;
	case 'V':
	case 'v':	goto yy183;
	default:	goto yy27;
	}
yy128:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy184;
	default:	goto yy27;
	}
yy129:
	++YYCURSOR;
#line 59 "scanner.re"
	{ value.token = TOKEN_ZERO; return value; }
#line 1086 "scanner.c"
yy131:
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '/':	goto yy185;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy186;
	default:	goto yy53;
	}
yy132:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
yy133:
	switch (yych) {
	case '.':	goto yy26;
	case '/':	goto yy28;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy132;
	default:	goto yy11;
	}
yy134:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy187;
	default:	goto yy27;
	}
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy188;
	default:	goto yy27;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy189;
	default:	goto yy27;
	}
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy190;
	default:	goto yy27;
	}
yy138:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy191;
	default:	goto yy27;
	}
yy139:
	++YYCURSOR;
#line 55 "scanner.re"
	{ value.token = TOKEN_AND_A; return value; }
#line 1164 "scanner.c"
yy141:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy192;
	default:	goto yy27;
	}
yy142:
	yyaccept = 8;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy193;
	case 'H':
	case 'h':	goto yy194;
	case 'I':
	case 'i':	goto yy196;
	case 'Y':
	case 'y':	goto yy197;
	default:	goto yy143;
	}
yy143:
#line 67 "scanner.re"
	{ value.token = TOKEN_EIGHT; return value; }
#line 1189 "scanner.c"
yy144:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy199;
	default:	goto yy27;
	}
yy145:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy201;
	default:	goto yy27;
	}
yy146:
	++YYCURSOR;
#line 115 "scanner.re"
	{ value.token = TOKEN_FIFTH; return value; }
#line 1208 "scanner.c"
yy148:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy202;
	default:	goto yy27;
	}
yy149:
	++YYCURSOR;
#line 85 "scanner.re"
	{ value.token = TOKEN_FIFTY; return value; }
#line 1220 "scanner.c"
yy151:
	++YYCURSOR;
#line 102 "scanner.re"
	{ value.token = TOKEN_FIRST; return value; }
#line 1225 "scanner.c"
yy153:
	++YYCURSOR;
#line 83 "scanner.re"
	{ value.token = TOKEN_FORTY; return value; }
#line 1230 "scanner.c"
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy203;
	case 'H':
	case 'h':	goto yy204;
	case 'I':
	case 'i':	goto yy206;
	case 'Y':
	case 'y':	goto yy207;
	default:	goto yy27;
	}
yy156:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy209;
	default:	goto yy27;
	}
yy157:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy210;
	default:	goto yy27;
	}
yy158:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy211;
	default:	goto yy27;
	}
yy159:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy212;
	case 'H':
	case 'h':	goto yy213;
	case 'I':
	case 'i':	goto yy215;
	case 'Y':
	case 'y':	goto yy216;
	default:	goto yy27;
	}
yy160:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy218;
	default:	goto yy27;
	}
yy161:
	++YYCURSOR;
#line 120 "scanner.re"
	{ value.token = TOKEN_NINTH; return value; }
#line 1289 "scanner.c"
yy163:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy219;
	default:	goto yy27;
	}
yy164:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy220;
	default:	goto yy27;
	}
yy165:
	yyaccept = 9;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy222;
	default:	goto yy166;
	}
yy166:
#line 66 "scanner.re"
	{ value.token = TOKEN_SEVEN; return value; }
#line 1315 "scanner.c"
yy167:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy223;
	default:	goto yy27;
	}
yy168:
	++YYCURSOR;
#line 116 "scanner.re"
	{ value.token = TOKEN_SIXTH; return value; }
#line 1327 "scanner.c"
yy170:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy224;
	default:	goto yy27;
	}
yy171:
	++YYCURSOR;
#line 86 "scanner.re"
	{ value.token = TOKEN_SIXTY; return value; }
#line 1339 "scanner.c"
yy173:
	++YYCURSOR;
#line 122 "scanner.re"
	{ value.token = TOKEN_TENTH; return value; }
#line 1344 "scanner.c"
yy175:
	++YYCURSOR;
#line 113 "scanner.re"
	{ value.token = TOKEN_THIRD; return value; }
#line 1349 "scanner.c"
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy225;
	case 'I':
	case 'i':	goto yy226;
	case 'Y':
	case 'y':	goto yy227;
	default:	goto yy27;
	}
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy229;
	default:	goto yy27;
	}
yy179:
	++YYCURSOR;
#line 62 "scanner.re"
	{ value.token = TOKEN_THREE; return value; }
#line 1372 "scanner.c"
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy230;
	default:	goto yy27;
	}
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy231;
	default:	goto yy27;
	}
yy183:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy232;
	default:	goto yy27;
	}
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy234;
	case 'Y':
	case 'y':	goto yy235;
	default:	goto yy27;
	}
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy237;
	default:	goto yy27;
	}
yy186:
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '/':	goto yy185;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy238;
	default:	goto yy53;
	}
yy187:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy239;
	default:	goto yy27;
	}
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy240;
	default:	goto yy27;
	}
yy189:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy241;
	default:	goto yy27;
	}
yy190:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy242;
	default:	goto yy27;
	}
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy243;
	default:	goto yy27;
	}
yy192:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy244;
	default:	goto yy27;
	}
yy193:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy246;
	default:	goto yy27;
	}
yy194:
	++YYCURSOR;
#line 118 "scanner.re"
	{ value.token = TOKEN_EIGHTH; return value; }
#line 1488 "scanner.c"
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy247;
	default:	goto yy27;
	}
yy197:
	++YYCURSOR;
#line 88 "scanner.re"
	{ value.token = TOKEN_EIGHTY; return value; }
#line 1500 "scanner.c"
yy199:
	yyaccept = 10;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy248;
	default:	goto yy200;
	}
yy200:
#line 70 "scanner.re"
	{ value.token = TOKEN_ELEVEN; return value; }
#line 1512 "scanner.c"
yy201:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy249;
	default:	goto yy27;
	}
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy251;
	default:	goto yy27;
	}
yy203:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy252;
	default:	goto yy27;
	}
yy204:
	++YYCURSOR;
#line 114 "scanner.re"
	{ value.token = TOKEN_FOURTH; return value; }
#line 1538 "scanner.c"
yy206:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy253;
	default:	goto yy27;
	}
yy207:
	++YYCURSOR;
#line 84 "scanner.re"
	{ value.token = TOKEN_FORTY; return value; }
#line 1550 "scanner.c"
yy209:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy254;
	default:	goto yy27;
	}
yy210:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy256;
	default:	goto yy27;
	}
yy211:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'V':
	case 'v':	goto yy258;
	default:	goto yy27;
	}
yy212:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy259;
	default:	goto yy27;
	}
yy213:
	++YYCURSOR;
#line 119 "scanner.re"
	{ value.token = TOKEN_NINTH; return value; }
#line 1583 "scanner.c"
yy215:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy260;
	default:	goto yy27;
	}
yy216:
	++YYCURSOR;
#line 89 "scanner.re"
	{ value.token = TOKEN_NINETY; return value; }
#line 1595 "scanner.c"
yy218:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy261;
	default:	goto yy27;
	}
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy263;
	default:	goto yy27;
	}
yy220:
	++YYCURSOR;
#line 103 "scanner.re"
	{
            if (state->parse_second) {
                // dont' parse "second" by default. easiest way to do this is to
                // treat it as a character token
                value.token = TOKEN_CHARACTERS;
            } else {
                value.token = TOKEN_SECOND;
            }
            return value;
        }
#line 1623 "scanner.c"
yy222:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy265;
	case 'H':
	case 'h':	goto yy266;
	case 'I':
	case 'i':	goto yy268;
	case 'Y':
	case 'y':	goto yy269;
	default:	goto yy27;
	}
yy223:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy271;
	default:	goto yy27;
	}
yy224:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy273;
	default:	goto yy27;
	}
yy225:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy274;
	default:	goto yy27;
	}
yy226:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy275;
	default:	goto yy27;
	}
yy227:
	++YYCURSOR;
#line 82 "scanner.re"
	{ value.token = TOKEN_THIRTY; return value; }
#line 1669 "scanner.c"
yy229:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy276;
	default:	goto yy27;
	}
yy230:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy277;
	default:	goto yy27;
	}
yy231:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy278;
	default:	goto yy27;
	}
yy232:
	++YYCURSOR;
#line 71 "scanner.re"
	{ value.token = TOKEN_TWELVE; return value; }
#line 1695 "scanner.c"
yy234:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy280;
	default:	goto yy27;
	}
yy235:
	++YYCURSOR;
#line 81 "scanner.re"
	{ value.token = TOKEN_TWENTY; return value; }
#line 1707 "scanner.c"
yy237:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy281;
	default:	goto yy27;
	}
yy238:
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '/':	goto yy185;
	default:	goto yy52;
	}
yy239:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy283;
	default:	goto yy27;
	}
yy240:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy284;
	default:	goto yy27;
	}
yy241:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy285;
	default:	goto yy27;
	}
yy242:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy286;
	default:	goto yy27;
	}
yy243:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy287;
	default:	goto yy27;
	}
yy244:
	yyaccept = 11;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy288;
	default:	goto yy245;
	}
yy245:
#line 98 "scanner.re"
	{ value.token = TOKEN_BILLION; return value; }
#line 1776 "scanner.c"
yy246:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy289;
	default:	goto yy27;
	}
yy247:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy291;
	default:	goto yy27;
	}
yy248:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy292;
	default:	goto yy27;
	}
yy249:
	yyaccept = 12;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy294;
	default:	goto yy250;
	}
yy250:
#line 74 "scanner.re"
	{ value.token = TOKEN_FIFTEEN; return value; }
#line 1809 "scanner.c"
yy251:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy295;
	default:	goto yy27;
	}
yy252:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy297;
	default:	goto yy27;
	}
yy253:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy299;
	default:	goto yy27;
	}
yy254:
	yyaccept = 13;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy300;
	default:	goto yy255;
	}
yy255:
#line 92 "scanner.re"
	{ value.token = TOKEN_HUNDRED; return value; }
#line 1842 "scanner.c"
yy256:
	yyaccept = 14;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy301;
	default:	goto yy257;
	}
yy257:
#line 96 "scanner.re"
	{ value.token = TOKEN_MILLION; return value; }
#line 1854 "scanner.c"
yy258:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy302;
	default:	goto yy27;
	}
yy259:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy304;
	default:	goto yy27;
	}
yy260:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy306;
	default:	goto yy27;
	}
yy261:
	++YYCURSOR;
#line 79 "scanner.re"
	{ value.token = TOKEN_NINETEEN; return value; }
#line 1880 "scanner.c"
yy263:
	++YYCURSOR;
#line 148 "scanner.re"
	{ value.token = TOKEN_QUARTER; return value; }
#line 1885 "scanner.c"
yy265:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy307;
	default:	goto yy27;
	}
yy266:
	++YYCURSOR;
#line 117 "scanner.re"
	{ value.token = TOKEN_SEVENTH; return value; }
#line 1897 "scanner.c"
yy268:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy308;
	default:	goto yy27;
	}
yy269:
	++YYCURSOR;
#line 87 "scanner.re"
	{ value.token = TOKEN_SEVENTY; return value; }
#line 1909 "scanner.c"
yy271:
	yyaccept = 15;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy309;
	default:	goto yy272;
	}
yy272:
#line 75 "scanner.re"
	{ value.token = TOKEN_SIXTEEN; return value; }
#line 1921 "scanner.c"
yy273:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy310;
	default:	goto yy27;
	}
yy274:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy312;
	default:	goto yy27;
	}
yy275:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy314;
	default:	goto yy27;
	}
yy276:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy315;
	default:	goto yy27;
	}
yy277:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy317;
	default:	goto yy27;
	}
yy278:
	++YYCURSOR;
#line 124 "scanner.re"
	{ value.token = TOKEN_TWELFTH; return value; }
#line 1961 "scanner.c"
yy280:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy319;
	default:	goto yy27;
	}
yy281:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy320;
	default:	goto yy282;
	}
yy282:
#line 50 "scanner.re"
	{ value.token = TOKEN_CHARACTERS; return value; }
#line 1987 "scanner.c"
yy283:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy321;
	default:	goto yy27;
	}
yy284:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy323;
	default:	goto yy27;
	}
yy285:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy325;
	default:	goto yy27;
	}
yy286:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy327;
	default:	goto yy27;
	}
yy287:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy328;
	default:	goto yy27;
	}
yy288:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy329;
	default:	goto yy27;
	}
yy289:
	yyaccept = 16;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy331;
	default:	goto yy290;
	}
yy290:
#line 77 "scanner.re"
	{ value.token = TOKEN_EIGHTEEN; return value; }
#line 2041 "scanner.c"
yy291:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy332;
	default:	goto yy27;
	}
yy292:
	++YYCURSOR;
#line 123 "scanner.re"
	{ value.token = TOKEN_ELEVENTH; return value; }
#line 2053 "scanner.c"
yy294:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy334;
	default:	goto yy27;
	}
yy295:
	++YYCURSOR;
#line 136 "scanner.re"
	{ value.token = TOKEN_FIFTIETH; return value; }
#line 2065 "scanner.c"
yy297:
	yyaccept = 17;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy336;
	default:	goto yy298;
	}
yy298:
#line 73 "scanner.re"
	{ value.token = TOKEN_FOURTEEN; return value; }
#line 2077 "scanner.c"
yy299:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy337;
	default:	goto yy27;
	}
yy300:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy339;
	default:	goto yy27;
	}
yy301:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy341;
	default:	goto yy27;
	}
yy302:
	++YYCURSOR;
#line 57 "scanner.re"
	{ value.token = TOKEN_NEGATIVE; return value; }
#line 2103 "scanner.c"
yy304:
	yyaccept = 18;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy343;
	default:	goto yy305;
	}
yy305:
#line 78 "scanner.re"
	{ value.token = TOKEN_NINETEEN; return value; }
#line 2115 "scanner.c"
yy306:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy344;
	default:	goto yy27;
	}
yy307:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy346;
	default:	goto yy27;
	}
yy308:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy348;
	default:	goto yy27;
	}
yy309:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy349;
	default:	goto yy27;
	}
yy310:
	++YYCURSOR;
#line 137 "scanner.re"
	{ value.token = TOKEN_SIXTIETH; return value; }
#line 2148 "scanner.c"
yy312:
	yyaccept = 19;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy351;
	default:	goto yy313;
	}
yy313:
#line 72 "scanner.re"
	{ value.token = TOKEN_THIRTEEN; return value; }
#line 2160 "scanner.c"
yy314:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy352;
	default:	goto yy27;
	}
yy315:
	yyaccept = 20;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy354;
	default:	goto yy316;
	}
yy316:
#line 94 "scanner.re"
	{ value.token = TOKEN_THOUSAND; return value; }
#line 2179 "scanner.c"
yy317:
	yyaccept = 21;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy355;
	default:	goto yy318;
	}
yy318:
#line 100 "scanner.re"
	{ value.token = TOKEN_TRILLION; return value; }
#line 2191 "scanner.c"
yy319:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy356;
	default:	goto yy27;
	}
yy320:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy358;
	default:	goto yy282;
	}
yy321:
	++YYCURSOR;
#line 97 "scanner.re"
	{ value.token = TOKEN_BILLION; return value; }
#line 2218 "scanner.c"
yy323:
	++YYCURSOR;
#line 91 "scanner.re"
	{ value.token = TOKEN_HUNDRED; return value; }
#line 2223 "scanner.c"
yy325:
	++YYCURSOR;
#line 95 "scanner.re"
	{ value.token = TOKEN_MILLION; return value; }
#line 2228 "scanner.c"
yy327:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy359;
	default:	goto yy27;
	}
yy328:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy361;
	default:	goto yy27;
	}
yy329:
	++YYCURSOR;
#line 145 "scanner.re"
	{ value.token = TOKEN_BILLIONTH; return value; }
#line 2247 "scanner.c"
yy331:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy363;
	default:	goto yy27;
	}
yy332:
	++YYCURSOR;
#line 139 "scanner.re"
	{ value.token = TOKEN_EIGHTIETH; return value; }
#line 2259 "scanner.c"
yy334:
	++YYCURSOR;
#line 127 "scanner.re"
	{ value.token = TOKEN_FIFTEENTH; return value; }
#line 2264 "scanner.c"
yy336:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy365;
	default:	goto yy27;
	}
yy337:
	++YYCURSOR;
#line 135 "scanner.re"
	{ value.token = TOKEN_FOURTIETH; return value; }
#line 2276 "scanner.c"
yy339:
	++YYCURSOR;
#line 142 "scanner.re"
	{ value.token = TOKEN_HUNDREDTH; return value; }
#line 2281 "scanner.c"
yy341:
	++YYCURSOR;
#line 144 "scanner.re"
	{ value.token = TOKEN_MILLIONTH; return value; }
#line 2286 "scanner.c"
yy343:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy367;
	default:	goto yy27;
	}
yy344:
	++YYCURSOR;
#line 140 "scanner.re"
	{ value.token = TOKEN_NINETIETH; return value; }
#line 2298 "scanner.c"
yy346:
	yyaccept = 22;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy369;
	default:	goto yy347;
	}
yy347:
#line 76 "scanner.re"
	{ value.token = TOKEN_SEVENTEEN; return value; }
#line 2310 "scanner.c"
yy348:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy370;
	default:	goto yy27;
	}
yy349:
	++YYCURSOR;
#line 128 "scanner.re"
	{ value.token = TOKEN_SIXTEENTH; return value; }
#line 2322 "scanner.c"
yy351:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy372;
	default:	goto yy27;
	}
yy352:
	++YYCURSOR;
#line 134 "scanner.re"
	{ value.token = TOKEN_THIRTIETH; return value; }
#line 2334 "scanner.c"
yy354:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy374;
	default:	goto yy27;
	}
yy355:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy376;
	default:	goto yy27;
	}
yy356:
	++YYCURSOR;
#line 133 "scanner.re"
	{ value.token = TOKEN_TWENTIETH; return value; }
#line 2353 "scanner.c"
yy358:
	yych = *++YYCURSOR;
	goto yy282;
yy359:
	++YYCURSOR;
#line 93 "scanner.re"
	{ value.token = TOKEN_THOUSAND; return value; }
#line 2361 "scanner.c"
yy361:
	++YYCURSOR;
#line 99 "scanner.re"
	{ value.token = TOKEN_TRILLION; return value; }
#line 2366 "scanner.c"
yy363:
	++YYCURSOR;
#line 130 "scanner.re"
	{ value.token = TOKEN_EIGHTEENTH; return value; }
#line 2371 "scanner.c"
yy365:
	++YYCURSOR;
#line 126 "scanner.re"
	{ value.token = TOKEN_FOURTEENTH; return value; }
#line 2376 "scanner.c"
yy367:
	++YYCURSOR;
#line 131 "scanner.re"
	{ value.token = TOKEN_NINETEENTH; return value; }
#line 2381 "scanner.c"
yy369:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy378;
	default:	goto yy27;
	}
yy370:
	++YYCURSOR;
#line 138 "scanner.re"
	{ value.token = TOKEN_SEVENTIETH; return value; }
#line 2393 "scanner.c"
yy372:
	++YYCURSOR;
#line 125 "scanner.re"
	{ value.token = TOKEN_THIRTEENTH; return value; }
#line 2398 "scanner.c"
yy374:
	++YYCURSOR;
#line 143 "scanner.re"
	{ value.token = TOKEN_THOUSANDTH; return value; }
#line 2403 "scanner.c"
yy376:
	++YYCURSOR;
#line 146 "scanner.re"
	{ value.token = TOKEN_TRILLIONTH; return value; }
#line 2408 "scanner.c"
yy378:
	++YYCURSOR;
#line 129 "scanner.re"
	{ value.token = TOKEN_SEVENTEENTH; return value; }
#line 2413 "scanner.c"
}
#line 197 "scanner.re"

}
